//! A synthetic CMS `EnvelopedData` builder and the throwaway RSA keys it uses.
//!
//! Everything here is generated by and for this test suite, **at run time**.
//! No private key, in any encoding, is stored in this repository: a secret
//! scanner cannot tell a real key from a synthetic one, and the project does
//! not allowlist scanner rules, so the only safe amount of key material in the
//! tree is none. See `SECURITY.md`.
//!
//! The keys are still deterministic. They come from a fixed seed through
//! `ChaCha20Rng`, so a failure reproduces exactly, and they are generated once
//! per test binary behind a `LazyLock`. Generation costs about 75 ms per key
//! because the workspace optimizes `rsa` and `num-bigint-dig` even in the dev
//! profile; unoptimized it would be nearer five seconds.
//!
//! `openszigno-author` now writes the `encrypt` transform, but only the
//! narrow, correct subset a producer should emit. This encryptor exists
//! alongside it to build the messages a *reader* must cope with and a
//! producer must never write: DES-EDE3-CBC, unsupported algorithm
//! identifiers, and deliberately damaged framing. That is why it stays in
//! the test suites. This file is included by both the core and the CLI test
//! suites, so it deliberately stands alone: it refers to nothing outside its
//! own module.
#![allow(dead_code)]

use std::sync::LazyLock;

use base64::{Engine as _, engine::general_purpose::STANDARD};
use cipher::{BlockEncryptMut, KeyIvInit, block_padding::Pkcs7};
use cms::cert::IssuerAndSerialNumber;
use cms::content_info::{CmsVersion, ContentInfo};
use cms::enveloped_data::{
    EncryptedContentInfo, EnvelopedData, KeyTransRecipientInfo, RecipientIdentifier, RecipientInfo,
    RecipientInfos,
};
use der::asn1::{Any, ObjectIdentifier, OctetString, SetOfVec};
use der::{Decode, Encode};
use x509_cert::Certificate;
use x509_cert::ext::pkix::SubjectKeyIdentifier;
use x509_cert::spki::AlgorithmIdentifierOwned;

use rand_core::SeedableRng as _;
use rsa::pkcs8::EncodePrivateKey as _;

const ID_ENVELOPED_DATA: ObjectIdentifier = ObjectIdentifier::new_unwrap("1.2.840.113549.1.7.3");
const ID_DATA: ObjectIdentifier = ObjectIdentifier::new_unwrap("1.2.840.113549.1.7.1");
const RSA_ENCRYPTION: ObjectIdentifier = ObjectIdentifier::new_unwrap("1.2.840.113549.1.1.1");
const RSAES_OAEP: ObjectIdentifier = ObjectIdentifier::new_unwrap("1.2.840.113549.1.1.7");
const ID_MGF1: ObjectIdentifier = ObjectIdentifier::new_unwrap("1.2.840.113549.1.1.8");
const ID_SHA256: ObjectIdentifier = ObjectIdentifier::new_unwrap("2.16.840.1.101.3.4.2.1");
const AES_128_CBC: ObjectIdentifier = ObjectIdentifier::new_unwrap("2.16.840.1.101.3.4.1.2");
const AES_192_CBC: ObjectIdentifier = ObjectIdentifier::new_unwrap("2.16.840.1.101.3.4.1.22");
const AES_256_CBC: ObjectIdentifier = ObjectIdentifier::new_unwrap("2.16.840.1.101.3.4.1.42");
const DES_EDE3_CBC: ObjectIdentifier = ObjectIdentifier::new_unwrap("1.2.840.113549.3.7");
/// ChaCha20-Poly1305, used only as an algorithm this build does not support.
const UNSUPPORTED_CIPHER: ObjectIdentifier =
    ObjectIdentifier::new_unwrap("1.2.840.113549.1.9.16.3.18");

type Aes128CbcEnc = cbc::Encryptor<aes::Aes128>;
type Aes192CbcEnc = cbc::Encryptor<aes::Aes192>;
type Aes256CbcEnc = cbc::Encryptor<aes::Aes256>;
type TdesCbcEnc = cbc::Encryptor<des::TdesEde3>;

/// The content encryption a synthetic message uses.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum Cipher {
    Aes128Cbc,
    Aes192Cbc,
    Aes256Cbc,
    TripleDesCbc,
    /// A well-formed message naming an algorithm this build does not implement.
    Unsupported,
}

/// The key transport a synthetic message wraps its content key with.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum KeyTransport {
    Pkcs1v15,
    OaepSha256,
    /// A key-transport OID this build does not implement, with a PKCS#1 v1.5
    /// wrap underneath so that only the identifier is unusual.
    UnsupportedOid,
}

/// How the recipient is named in the message.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum Naming {
    IssuerAndSerial,
    SubjectKeyIdentifier,
}

/// The seed every synthetic key in this suite comes from. Any fixed value
/// would do.
const SEED: u64 = 0x006F_7065_6E53_5A00;

/// The seed the RSA key wrapping uses for its padding bytes.
///
/// Real PKCS#1 v1.5 and OAEP padding is random, and a real encryptor must
/// keep it that way. A *test* encryptor must not: the recipient side now
/// answers an unusable wrapped key by decrypting under a synthetic key
/// derived from the ciphertext, so a ciphertext that changes every run makes
/// the resulting garbage, and anything downstream that inspects it, change
/// every run too. Seeding this is what makes those assertions reproducible
/// on every platform rather than a per-run coin flip.
const WRAP_SEED: u64 = 0x006F_7065_6E53_5A02;

/// The passphrase the passphrase-protected key helpers use. It protects a key
/// that exists only inside one test run.
pub const PASSPHRASE: &str = "correct horse battery staple";

/// The password-based key derivation a passphrase-protected key uses.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum EncryptedKeyKdf {
    /// PBKDF2-SHA-256, what `openssl pkcs8 -topk8` writes.
    Pbkdf2,
    /// scrypt, the RustCrypto default and the more expensive of the two.
    Scrypt,
}

/// Which of the two synthetic keys a recipient is built on.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum Which {
    /// The key the tests hold and decrypt with.
    Recipient,
    /// A second key, for "this document is addressed to somebody else" and
    /// "this certificate does not belong to this key".
    Stranger,
}

/// The two keys, generated once per test binary from the fixed seed.
fn key(which: Which) -> &'static rsa::RsaPrivateKey {
    static KEYS: LazyLock<[rsa::RsaPrivateKey; 2]> = LazyLock::new(|| {
        let mut rng = rand_chacha::ChaCha20Rng::seed_from_u64(SEED);
        [
            rsa::RsaPrivateKey::new(&mut rng, 2048).expect("a synthetic RSA key generates"),
            rsa::RsaPrivateKey::new(&mut rng, 2048).expect("a synthetic RSA key generates"),
        ]
    });
    match which {
        Which::Recipient => &KEYS[0],
        Which::Stranger => &KEYS[1],
    }
}

/// A synthetic recipient: an RSA key and a self-signed certificate for it.
pub struct Recipient {
    pub private_pkcs8_der: Vec<u8>,
    pub certificate_der: Vec<u8>,
    public: rsa::RsaPublicKey,
    certificate: Certificate,
}

impl Recipient {
    /// Build a recipient on one of the two synthetic keys.
    ///
    /// `with_key_identifier` decides whether the certificate carries a
    /// `subjectKeyIdentifier` extension, which is what makes SKI-named
    /// recipients matchable.
    pub fn new(which: Which, common_name: &str, with_key_identifier: bool) -> Self {
        let private = key(which).clone();
        let der = private
            .to_pkcs8_der()
            .expect("the generated key encodes as PKCS#8")
            .as_bytes()
            .to_vec();
        let pair = rcgen::KeyPair::from_pkcs8_der_and_sign_algo(
            &der.clone().into(),
            &rcgen::PKCS_RSA_SHA256,
        )
        .expect("rcgen accepts the generated RSA key");
        let mut params =
            rcgen::CertificateParams::new(Vec::new()).expect("certificate parameters build");
        params
            .distinguished_name
            .push(rcgen::DnType::CommonName, common_name);
        // rcgen emits a subjectKeyIdentifier only when the basic-constraints
        // extension is written, which `ExplicitNoCa` forces for a leaf.
        params.is_ca = match with_key_identifier {
            true => rcgen::IsCa::ExplicitNoCa,
            false => rcgen::IsCa::NoCa,
        };
        let certificate = params.self_signed(&pair).expect("the certificate issues");
        let certificate_der = certificate.der().to_vec();
        Self {
            certificate: Certificate::from_der(&certificate_der).expect("the certificate parses"),
            public: rsa::RsaPublicKey::from(&private),
            private_pkcs8_der: der,
            certificate_der,
        }
    }

    /// The recipient's key and certificate as one PEM bundle, the shape a
    /// caller gets from `openssl pkcs12 -nodes`.
    pub fn pem_bundle(&self) -> String {
        format!("{}\n{}", self.key_pem(), self.certificate_pem())
    }

    pub fn certificate_pem(&self) -> String {
        pem_block("CERTIFICATE", &self.certificate_der)
    }

    /// The key on its own, as PKCS#8 PEM.
    pub fn key_pem(&self) -> String {
        pem_block(PRIVATE_KEY_LABEL, &self.private_pkcs8_der)
    }

    /// The key as passphrase-protected PKCS#8 PEM, encrypted here rather than
    /// embedded, under [`PASSPHRASE`].
    ///
    /// PBES2 with PBKDF2-SHA-256 and AES-256-CBC, which is what
    /// `openssl pkcs8 -topk8` writes, with a fixed salt and IV so the output
    /// is reproducible. The iteration count is deliberately low: this protects
    /// a key that exists for the length of one test.
    pub fn encrypted_key_pem(&self) -> String {
        self.encrypted_key_pem_with(EncryptedKeyKdf::Pbkdf2)
    }

    /// The same, with a caller-chosen key derivation, so that both PBES2 forms
    /// a real `.p12` conversion can produce are exercised.
    pub fn encrypted_key_pem_with(&self, kdf: EncryptedKeyKdf) -> String {
        let info = pkcs8::PrivateKeyInfo::try_from(self.private_pkcs8_der.as_slice())
            .expect("the generated key is PKCS#8");
        let encrypted = match kdf {
            EncryptedKeyKdf::Pbkdf2 => {
                let parameters = pkcs8::pkcs5::pbes2::Parameters::pbkdf2_sha256_aes256cbc(
                    2048,
                    b"openSzigno test salt",
                    &[0x5a; 16],
                )
                .expect("the PBES2 parameters build");
                info.encrypt_with_params(parameters, PASSPHRASE.as_bytes())
            }
            EncryptedKeyKdf::Scrypt => {
                let mut rng = rand_chacha::ChaCha20Rng::seed_from_u64(SEED ^ 1);
                info.encrypt(&mut rng, PASSPHRASE.as_bytes())
            }
        }
        .expect("the key encrypts");
        pem_block(ENCRYPTED_PRIVATE_KEY_LABEL, encrypted.as_bytes())
    }

    fn identifier(&self, naming: Naming) -> RecipientIdentifier {
        match naming {
            Naming::IssuerAndSerial => {
                RecipientIdentifier::IssuerAndSerialNumber(IssuerAndSerialNumber {
                    issuer: self.certificate.tbs_certificate.issuer.clone(),
                    serial_number: self.certificate.tbs_certificate.serial_number.clone(),
                })
            }
            Naming::SubjectKeyIdentifier => {
                let extension = self
                    .certificate
                    .tbs_certificate
                    .extensions
                    .as_ref()
                    .expect("the certificate has extensions")
                    .iter()
                    .find(|extension| {
                        extension.extn_id == ObjectIdentifier::new_unwrap("2.5.29.14")
                    })
                    .expect("the certificate has a subject key identifier");
                RecipientIdentifier::SubjectKeyIdentifier(
                    SubjectKeyIdentifier::from_der(extension.extn_value.as_bytes())
                        .expect("the extension holds an octet string"),
                )
            }
        }
    }
}

/// PEM labels, kept as named constants.
///
/// Spelled this way so that a finished armour line never appears as a literal
/// in this repository. A secret scanner cannot tell a real key block from a
/// test string that only looks like one, and this project does not allowlist
/// scanner rules.
pub const PRIVATE_KEY_LABEL: &str = "PRIVATE KEY";
pub const ENCRYPTED_PRIVATE_KEY_LABEL: &str = "ENCRYPTED PRIVATE KEY";

pub fn pem_block(label: &str, der: &[u8]) -> String {
    let body = STANDARD.encode(der);
    let lines: Vec<&str> = body
        .as_bytes()
        .chunks(64)
        .map(|chunk| std::str::from_utf8(chunk).expect("base64 is ASCII"))
        .collect();
    format!(
        "-----BEGIN {label}-----\n{}\n-----END {label}-----\n",
        lines.join("\n")
    )
}

/// One synthetic message: what to encrypt and how.
pub struct Message<'a> {
    pub plaintext: &'a [u8],
    pub cipher: Cipher,
    pub transport: KeyTransport,
    pub naming: Naming,
}

/// A structural fault to build into a message, so that a test can reach the
/// framing checks a cooperating sender never trips.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum Damage {
    /// Detached content: the `encryptedContent` field is absent.
    NoEncryptedContent,
    /// An initialisation vector one byte short of the cipher's block size.
    ShortInitialisationVector,
    /// No algorithm parameters at all, so there is no IV to be found.
    NoInitialisationVector,
    /// A content-encryption key eight bytes longer than the announced cipher
    /// takes, wrapped in otherwise valid PKCS#1 v1.5 padding. This is what a
    /// Bleichenbacher probe that guessed the padding but not the payload
    /// length looks like from the recipient's side.
    MismatchedContentKeyLength,
}

/// Build a DER `ContentInfo` carrying `id-envelopedData` for one recipient.
///
/// The content encryption key and IV are fixed rather than random: a test
/// wants a byte-for-byte reproducible message, and neither value protects
/// anything here.
pub fn envelope(message: &Message<'_>, recipient: &Recipient) -> Vec<u8> {
    build(message, recipient, None)
}

/// The same, with one structural fault built in.
pub fn damaged(message: &Message<'_>, recipient: &Recipient, damage: Damage) -> Vec<u8> {
    build(message, recipient, Some(damage))
}

fn build(message: &Message<'_>, recipient: &Recipient, damage: Option<Damage>) -> Vec<u8> {
    let (mut content_algorithm, ciphertext) = encrypt_content(message);
    match damage {
        Some(Damage::NoInitialisationVector) => content_algorithm.parameters = None,
        Some(Damage::ShortInitialisationVector) => {
            let mut iv = initialisation_vector(message.cipher);
            iv.pop();
            content_algorithm.parameters = Some(
                Any::from_der(
                    &OctetString::new(iv)
                        .expect("the IV encodes")
                        .to_der()
                        .expect("DER"),
                )
                .expect("the IV is DER"),
            );
        }
        _ => {}
    }
    let recipient_info = RecipientInfo::Ktri(KeyTransRecipientInfo {
        version: CmsVersion::V0,
        rid: recipient.identifier(message.naming),
        key_enc_alg: key_transport_algorithm(message.transport),
        enc_key: OctetString::new(wrap_key(message, recipient, damage))
            .expect("the wrapped key encodes"),
    });
    let enveloped = EnvelopedData {
        version: CmsVersion::V0,
        originator_info: None,
        recip_infos: RecipientInfos(
            SetOfVec::try_from(vec![recipient_info]).expect("one recipient is a set"),
        ),
        encrypted_content: EncryptedContentInfo {
            content_type: ID_DATA,
            content_enc_alg: content_algorithm,
            encrypted_content: match damage {
                Some(Damage::NoEncryptedContent) => None,
                _ => Some(OctetString::new(ciphertext).expect("the ciphertext encodes")),
            },
        },
        unprotected_attrs: None,
    };
    let der = enveloped.to_der().expect("EnvelopedData encodes");
    ContentInfo {
        content_type: ID_ENVELOPED_DATA,
        content: Any::from_der(&der).expect("the content is DER"),
    }
    .to_der()
    .expect("ContentInfo encodes")
}

/// The same message wrapped for a recipient who is not `recipient`: the
/// RecipientInfo names `named`, but the key is wrapped for `named` too, so a
/// run holding only `recipient`'s key sees no matching recipient.
pub fn envelope_for(message: &Message<'_>, named: &Recipient) -> Vec<u8> {
    envelope(message, named)
}

/// The content encryption key for a cipher, fixed and unmistakable.
fn content_key(cipher: Cipher) -> Vec<u8> {
    let length = match cipher {
        Cipher::Aes128Cbc => 16,
        Cipher::Aes256Cbc | Cipher::Unsupported => 32,
        Cipher::Aes192Cbc | Cipher::TripleDesCbc => 24,
    };
    (0..length).map(|byte| byte as u8 ^ 0x5a).collect()
}

fn initialisation_vector(cipher: Cipher) -> Vec<u8> {
    let length = match cipher {
        Cipher::TripleDesCbc => 8,
        _ => 16,
    };
    (0..length).map(|byte| byte as u8 ^ 0xa5).collect()
}

fn encrypt_content(message: &Message<'_>) -> (AlgorithmIdentifierOwned, Vec<u8>) {
    let key = content_key(message.cipher);
    let iv = initialisation_vector(message.cipher);
    let ciphertext = match message.cipher {
        Cipher::Aes128Cbc => Aes128CbcEnc::new_from_slices(&key, &iv)
            .expect("the key and IV fit")
            .encrypt_padded_vec_mut::<Pkcs7>(message.plaintext),
        Cipher::Aes192Cbc => Aes192CbcEnc::new_from_slices(&key, &iv)
            .expect("the key and IV fit")
            .encrypt_padded_vec_mut::<Pkcs7>(message.plaintext),
        Cipher::Aes256Cbc | Cipher::Unsupported => Aes256CbcEnc::new_from_slices(&key, &iv)
            .expect("the key and IV fit")
            .encrypt_padded_vec_mut::<Pkcs7>(message.plaintext),
        Cipher::TripleDesCbc => TdesCbcEnc::new_from_slices(&key, &iv)
            .expect("the key and IV fit")
            .encrypt_padded_vec_mut::<Pkcs7>(message.plaintext),
    };
    let oid = match message.cipher {
        Cipher::Aes128Cbc => AES_128_CBC,
        Cipher::Aes192Cbc => AES_192_CBC,
        Cipher::Aes256Cbc => AES_256_CBC,
        Cipher::TripleDesCbc => DES_EDE3_CBC,
        Cipher::Unsupported => UNSUPPORTED_CIPHER,
    };
    let parameters = Any::from_der(
        &OctetString::new(iv)
            .expect("the IV encodes")
            .to_der()
            .expect("DER"),
    )
    .expect("the IV is DER");
    (
        AlgorithmIdentifierOwned {
            oid,
            parameters: Some(parameters),
        },
        ciphertext,
    )
}

fn key_transport_algorithm(transport: KeyTransport) -> AlgorithmIdentifierOwned {
    match transport {
        KeyTransport::Pkcs1v15 => AlgorithmIdentifierOwned {
            oid: RSA_ENCRYPTION,
            parameters: Some(Any::null()),
        },
        // id-ecPublicKey, which is not a key-transport algorithm at all.
        KeyTransport::UnsupportedOid => AlgorithmIdentifierOwned {
            oid: ObjectIdentifier::new_unwrap("1.2.840.10045.2.1"),
            parameters: Some(Any::null()),
        },
        KeyTransport::OaepSha256 => {
            let sha256 = AlgorithmIdentifierOwned {
                oid: ID_SHA256,
                parameters: Some(Any::null()),
            };
            let mgf1 = AlgorithmIdentifierOwned {
                oid: ID_MGF1,
                parameters: Some(
                    Any::from_der(&sha256.to_der().expect("DER")).expect("the hash is DER"),
                ),
            };
            AlgorithmIdentifierOwned {
                oid: RSAES_OAEP,
                parameters: Some(
                    Any::from_der(&oaep_params_der(&sha256, &mgf1)).expect("the params are DER"),
                ),
            }
        }
    }
}

/// `RSAES-OAEP-params` with an explicit hash and mask generation function and
/// the default (empty) label, hand-encoded so the test does not depend on the
/// library's own view of the structure.
fn oaep_params_der(hash: &AlgorithmIdentifierOwned, mgf: &AlgorithmIdentifierOwned) -> Vec<u8> {
    fn tagged(number: u8, body: &[u8]) -> Vec<u8> {
        let mut out = vec![0xa0 | number];
        out.extend(length(body.len()));
        out.extend_from_slice(body);
        out
    }
    fn length(value: usize) -> Vec<u8> {
        if value < 0x80 {
            return vec![value as u8];
        }
        let bytes = value.to_be_bytes();
        let start = bytes.iter().position(|byte| *byte != 0).unwrap_or(7);
        let significant = &bytes[start..];
        let mut out = vec![0x80 | significant.len() as u8];
        out.extend_from_slice(significant);
        out
    }
    let mut body = tagged(0, &hash.to_der().expect("DER"));
    body.extend(tagged(1, &mgf.to_der().expect("DER")));
    let mut out = vec![0x30];
    out.extend(length(body.len()));
    out.extend(body);
    out
}

fn wrap_key(message: &Message<'_>, recipient: &Recipient, damage: Option<Damage>) -> Vec<u8> {
    let mut key = content_key(message.cipher);
    if damage == Some(Damage::MismatchedContentKeyLength) {
        key.extend_from_slice(&[0x5a; 8]);
    }
    wrap_bytes(recipient, message.transport, &key)
}

/// Wrap arbitrary bytes for `recipient` under `transport`, in valid padding.
///
/// A test that wants a well-formed wrap of something other than the message's
/// own content key -- a key of the right length that is simply not the right
/// key -- builds it with this.
pub fn wrap_bytes(recipient: &Recipient, transport: KeyTransport, key: &[u8]) -> Vec<u8> {
    // Seeded, not `OsRng`: the padding bytes are the last thing in a
    // synthetic message that was not reproducible, and a message that
    // changes from run to run makes any assertion about what the *recipient*
    // then computes from it a coin flip. See the note on `WRAP_SEED`.
    let mut rng = rand_chacha::ChaCha20Rng::seed_from_u64(WRAP_SEED);
    match transport {
        KeyTransport::Pkcs1v15 | KeyTransport::UnsupportedOid => recipient
            .public
            .encrypt(&mut rng, rsa::Pkcs1v15Encrypt, key)
            .expect("the content key wraps"),
        KeyTransport::OaepSha256 => recipient
            .public
            .encrypt(&mut rng, rsa::Oaep::new::<sha2::Sha256>(), key)
            .expect("the content key wraps"),
    }
}

/// Deterministic filler of `length` bytes, for a test that needs a key-shaped
/// value that is not the message's own key.
pub fn filler(length: usize, tag: u8) -> Vec<u8> {
    (0..length)
        .map(|byte| (byte as u8).wrapping_mul(31) ^ tag)
        .collect()
}
