//! Builders for synthetic, unsigned test dossiers.
//!
//! Everything produced here is generated by the test suite itself: no real
//! dossier, signature, or personal data is involved. The helpers are shared by
//! several test binaries, so some are unused in any single one.
#![allow(dead_code)]

use std::io::Write;

use base64::{Engine as _, engine::general_purpose::STANDARD};

/// The committed plain fixture, for tests that patch one detail of a
/// known-good dossier.
pub const PLAIN: &str = include_str!("../../../../tests/fixtures/plain-base64.es3");

/// Wrap already rendered `<es:Document>` blocks in a minimal valid dossier.
pub fn dossier_with(documents: &str) -> String {
    dossier_with_profile("Unsigned synthetic fixture", documents)
}

/// Same as [`dossier_with`], with a caller-chosen dossier title.
pub fn dossier_with_profile(title: &str, documents: &str) -> String {
    format!(
        r#"<?xml version="1.0" encoding="UTF-8"?>
<es:Dossier xmlns:es="https://www.microsec.hu/ds/e-szigno30#" xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
<es:DossierProfile Id="DossierProfile1" OBJREF="Object0"><es:Title>{title}</es:Title><es:CreationDate>2026-01-01T00:00:00Z</es:CreationDate></es:DossierProfile>
<es:Documents Id="Object0">{documents}</es:Documents>
</es:Dossier>"#
    )
}

/// Render one `<es:Document>` block with fully controllable metadata.
pub fn document(
    index: usize,
    title: &str,
    extension: Option<&str>,
    source_size: u64,
    transforms: &[&str],
    payload: &str,
) -> String {
    let extension = extension.map_or_else(String::new, |value| format!(" extension=\"{value}\""));
    let transforms: String = transforms
        .iter()
        .map(|algorithm| format!("<es:Transform Algorithm=\"{algorithm}\"/>"))
        .collect();
    format!(
        concat!(
            "<es:Document><es:DocumentProfile Id=\"DocumentProfile{index}\" ",
            "OBJREF=\"DocumentObject{index}\"><es:Title>{title}</es:Title>",
            "<es:CreationDate>2026-01-01T00:00:00Z</es:CreationDate>",
            "<es:Format><es:MIME-Type type=\"text\" subtype=\"plain\"{extension}/></es:Format>",
            "<es:SourceSize sizeValue=\"{source_size}\" sizeUnit=\"B\"/>",
            "<es:BaseTransform>{transforms}</es:BaseTransform></es:DocumentProfile>",
            "<ds:Object Id=\"DocumentObject{index}\">{payload}</ds:Object></es:Document>"
        ),
        index = index,
        title = title,
        extension = extension,
        source_size = source_size,
        transforms = transforms,
        payload = payload,
    )
}

/// Render one `<es:Document>` whose profile carries no `SourceSize`.
pub fn document_without_source_size(index: usize, title: &str, payload: &[u8]) -> String {
    let rendered = document(
        index,
        title,
        Some("txt"),
        payload.len() as u64,
        &["base64"],
        &STANDARD.encode(payload),
    );
    let start = rendered
        .find("<es:SourceSize")
        .expect("the block has a source size");
    let end = rendered[start..].find("/>").expect("the element is empty") + start + 2;
    format!("{}{}", &rendered[..start], &rendered[end..])
}

/// A one-document dossier whose payload is `contents` under `base64`.
pub fn base64_dossier(contents: &[u8]) -> String {
    dossier_with(&document(
        1,
        "payload.txt",
        Some("txt"),
        contents.len() as u64,
        &["base64"],
        &STANDARD.encode(contents),
    ))
}

/// A one-document dossier whose payload is `archive` under `zip -> base64`.
pub fn zip_dossier(archive: &[u8], source_size: u64) -> String {
    dossier_with(&document(
        1,
        "member.bin",
        Some("bin"),
        source_size,
        &["zip", "base64"],
        &STANDARD.encode(archive),
    ))
}

/// Build a ZIP archive holding exactly one member.
pub fn single_member_zip(
    name: &str,
    contents: &[u8],
    options: zip::write::SimpleFileOptions,
) -> Vec<u8> {
    let mut archive = std::io::Cursor::new(Vec::new());
    {
        let mut writer = zip::ZipWriter::new(&mut archive);
        writer.start_file(name, options).expect("member starts");
        writer.write_all(contents).expect("member is writable");
        writer.finish().expect("archive finishes");
    }
    archive.into_inner()
}

/// The deflate options used for compressible test members.
pub fn deflated() -> zip::write::SimpleFileOptions {
    zip::write::SimpleFileOptions::default().compression_method(zip::CompressionMethod::Deflated)
}

/// The stored (uncompressed) options used for incompressible test members.
pub fn stored() -> zip::write::SimpleFileOptions {
    zip::write::SimpleFileOptions::default().compression_method(zip::CompressionMethod::Stored)
}

/// Overwrite the size fields of a single-member archive in both the local
/// header and the central directory, so that a payload can claim a size it
/// does not have. Header sizes are attacker-controlled in real input.
pub fn forge_zip_sizes(archive: &mut [u8], compressed: Option<u32>, uncompressed: Option<u32>) {
    assert_eq!(
        &archive[..4],
        b"PK\x03\x04",
        "local file header is expected"
    );
    let central = archive
        .windows(4)
        .position(|window| window == b"PK\x01\x02")
        .expect("central directory is present");
    for (offset, value) in [
        (18, compressed),
        (22, uncompressed),
        (central + 20, compressed),
        (central + 24, uncompressed),
    ] {
        if let Some(value) = value {
            archive[offset..offset + 4].copy_from_slice(&value.to_le_bytes());
        }
    }
}

/// The committed nesting fixture.
pub const NESTED: &str = include_str!("../../../../tests/fixtures/nested-dossier.es3");

/// The committed compatible-namespace fixture.
pub const COMPATIBLE: &str = include_str!("../../../../tests/fixtures/compatible-namespace.es3");

/// A company-court namespace generation, for allow-list tests.
pub const CEGELJARAS_2014: &str = "http://www.e-cegjegyzek.hu/2014/e-cegeljaras#";

/// Rewrite a default-namespace dossier into another namespace.
///
/// The `es:` prefix keeps its spelling; only the URI it is bound to changes,
/// which is exactly what a compatible profile does.
pub fn in_namespace(dossier: &str, namespace: &str) -> String {
    dossier.replace(
        "xmlns:es=\"https://www.microsec.hu/ds/e-szigno30#\"",
        &format!("xmlns:es=\"{namespace}\""),
    )
}

/// One `<es:Document>` whose payload is another complete dossier.
///
/// The subtype and extension are caller-chosen, so a test can exercise
/// detection by media type, by extension, or by content sniffing alone.
pub fn nesting_document(inner: &str, subtype: &str, extension: Option<&str>) -> String {
    let inner = inner.as_bytes();
    let extension = extension.map_or_else(String::new, |value| format!(" extension=\"{value}\""));
    format!(
        concat!(
            "<es:Document><es:DocumentProfile Id=\"DocumentProfile1\" ",
            "OBJREF=\"DocumentObject1\"><es:Title>court</es:Title>",
            "<es:CreationDate>2026-01-01T00:00:00Z</es:CreationDate>",
            "<es:Format><es:MIME-Type type=\"application\" subtype=\"{subtype}\"{extension}/></es:Format>",
            "<es:SourceSize sizeValue=\"{size}\" sizeUnit=\"B\"/>",
            "<es:BaseTransform><es:Transform Algorithm=\"base64\"/></es:BaseTransform>",
            "</es:DocumentProfile><ds:Object Id=\"DocumentObject1\">{payload}</ds:Object></es:Document>"
        ),
        subtype = subtype,
        extension = extension,
        size = inner.len(),
        payload = STANDARD.encode(inner),
    )
}

/// A one-document dossier whose only document embeds `inner`.
pub fn nesting_dossier(inner: &str, subtype: &str, extension: Option<&str>) -> String {
    dossier_with(&nesting_document(inner, subtype, extension))
}
