//! ETSI TS 119 612 trusted lists: anchor loading, service status over time,
//! qualified determination, and the list's own signature.
//!
//! Every list here is generated by the test helper. The real EU and Hungarian
//! lists in `refs/trust` are read only as documentation of the schema, never by
//! the suite: they change daily, and asserting anything about a real trust
//! service provider would make this suite a statement about that provider.

mod common;

use common::{
    CertSpec, DossierSpec, STATUS_GRANTED, STATUS_UNDER_SUPERVISION, STATUS_WITHDRAWN,
    SVCTYPE_TSA_QTST, SigSpec, SigningCertificateSpec, TestKey, TlService, TrustListSpec, build,
    build_trust_list, document_signature, issued_by, keys, qc_statements_extension, rsa_key,
    self_signed,
};
use openszigno_verify::codes::{CheckCode, CheckStatus};
use openszigno_verify::{
    FixedClock, MemoryRevocationStore, MemoryTrustStore, RoxmltreeC14n, TrustAnchorOrigin,
    VerifyOptions, VerifyReport, parse_rfc3339, verify,
};
use rcgen::BasicConstraints;

const AT: &str = "2020-06-02T00:00:00Z";

struct Pki {
    root_der: Vec<u8>,
    signer_der: Vec<u8>,
    signer_key: TestKey,
    tl_signer_der: Vec<u8>,
}

/// `not_before` decides whether the signing certificate is treated as
/// post-eIDAS, and `qc` decides which QCStatements it asserts.
fn pki(not_before: (i32, u8, u8), qc: &[&str]) -> Pki {
    let root_key = rsa_key(keys::ROOT_RSA2048);
    let signer_key = rsa_key(keys::SIGNER_RSA2048);

    let root = self_signed(
        &CertSpec::ca(
            "openSzigno Test Qualified CA",
            BasicConstraints::Unconstrained,
        ),
        &root_key,
    );
    let mut signer_spec = CertSpec::signer("openSzigno Test Signer");
    signer_spec.not_before = not_before;
    if !qc.is_empty() {
        signer_spec.custom_extensions = vec![qc_statements_extension(qc)];
    }
    let signer = issued_by(&signer_spec, &signer_key, &root, &root_key);
    let tl_signer = self_signed(
        &CertSpec::signer("openSzigno Test Trusted List Signer"),
        &rsa_key(keys::SECOND_RSA2048),
    );

    Pki {
        root_der: root.der,
        signer_der: signer.der,
        signer_key,
        tl_signer_der: tl_signer.der,
    }
}

fn signature(pki: &Pki) -> SigSpec {
    let mut signature = document_signature(vec![pki.signer_der.clone()]);
    signature.signing_certificate = Some(SigningCertificateSpec::v1(pki.signer_der.clone()));
    signature
}

fn dossier(signature: SigSpec, key: &TestKey) -> String {
    let spec = DossierSpec {
        document_signature: Some(signature),
        ..Default::default()
    };
    build(&spec, &[("doc", key)])
}

/// Load one trusted list and verify a dossier against the anchors it yields.
fn run_with_list(xml: &str, list: &str, signer: Option<&[u8]>, time: &str) -> VerifyReport {
    let backend = RoxmltreeC14n;
    let loaded = openszigno_verify::trustlist::load(list.as_bytes(), signer, &backend)
        .expect("the synthetic trusted list loads");
    let mut trust = MemoryTrustStore::default();
    for check in loaded.checks {
        trust.push_check(check);
    }
    trust.extend_anchors(loaded.anchors);

    let revocation = MemoryRevocationStore::default();
    let clock = FixedClock(parse_rfc3339(time).expect("the fixed time parses"));
    let mut options = VerifyOptions::new(&clock, &trust, &revocation, &backend);
    options.requested_time = Some(time.to_owned());
    verify(xml.as_bytes(), &options).expect("the dossier parses structurally")
}

fn codes(report: &VerifyReport) -> Vec<String> {
    report
        .checks
        .iter()
        .chain(
            report
                .signatures
                .iter()
                .flat_map(|signature| signature.checks.iter()),
        )
        .map(|check| format!("{}={}", check.code.as_str(), check.status.as_str()))
        .collect()
}

fn assert_check(report: &VerifyReport, code: CheckCode, status: CheckStatus) {
    let seen = codes(report);
    assert!(
        seen.contains(&format!("{}={}", code.as_str(), status.as_str())),
        "expected {}={}; got {seen:?}",
        code.as_str(),
        status.as_str()
    );
}

// ---------------------------------------------------------------------------
// Loading
// ---------------------------------------------------------------------------

/// A granted CA/QC service contributes its digital identity as a trust anchor,
/// and the report says the anchor came from a trusted list rather than from a
/// directory somebody filled in.
#[test]
fn a_granted_ca_qc_service_supplies_an_anchor() {
    let pki = pki((2019, 1, 1), &["0.4.0.1862.1.1"]);
    let list = build_trust_list(&TrustListSpec::new(vec![TlService::ca_qc(
        "openSzigno Test Qualified CA",
        pki.root_der.clone(),
    )]));
    let xml = dossier(signature(&pki), &pki.signer_key);
    let report = run_with_list(&xml, &list, None, AT);

    assert_check(&report, CheckCode::CertPathOk, CheckStatus::Passed);
    assert_check(&report, CheckCode::TrustListLoaded, CheckStatus::Info);
    let anchor = report.signatures[0]
        .chain
        .last()
        .expect("the chain ends at an anchor");
    assert!(anchor.is_trust_anchor);
    assert_eq!(
        anchor.trust_anchor_origin,
        Some(TrustAnchorOrigin::TrustList)
    );
}

/// The list's metadata is read, so a result can cite exactly which snapshot it
/// relied on.
#[test]
fn the_list_metadata_is_read() {
    let pki = pki((2019, 1, 1), &[]);
    let list = build_trust_list(&TrustListSpec::new(vec![TlService::ca_qc(
        "openSzigno Test Qualified CA",
        pki.root_der.clone(),
    )]));
    let loaded = openszigno_verify::trustlist::load(list.as_bytes(), None, &RoxmltreeC14n)
        .expect("the list loads");
    assert_eq!(loaded.territory.as_deref(), Some("HU"));
    assert_eq!(loaded.sequence_number, Some(7));
    assert_eq!(loaded.issue_date.as_deref(), Some("2020-01-01T00:00:00Z"));
    assert_eq!(loaded.next_update.as_deref(), Some("2021-01-01T00:00:00Z"));
    assert_eq!(loaded.anchors.len(), 1);
}

/// A `DigitalId` that only names a subject supplies no certificate, so it
/// supplies no anchor. The verifier will not go looking for one.
#[test]
fn a_digital_id_without_a_certificate_supplies_no_anchor() {
    let mut service = TlService::ca_qc("named only", Vec::new());
    service.certificates = Vec::new();
    service.subject_name_only = true;
    let list = build_trust_list(&TrustListSpec::new(vec![service]));
    let loaded = openszigno_verify::trustlist::load(list.as_bytes(), None, &RoxmltreeC14n)
        .expect("the list loads");
    assert!(loaded.anchors.is_empty());
}

/// A service of a type this build does not read — a qualified timestamping
/// authority is read, but nothing else is — contributes nothing.
#[test]
fn a_tsa_qtst_service_is_also_read() {
    let pki = pki((2019, 1, 1), &[]);
    let mut service = TlService::ca_qc("openSzigno Test QTSA", pki.root_der.clone());
    service.service_type = SVCTYPE_TSA_QTST.to_owned();
    let list = build_trust_list(&TrustListSpec::new(vec![service]));
    let loaded = openszigno_verify::trustlist::load(list.as_bytes(), None, &RoxmltreeC14n)
        .expect("the list loads");
    assert_eq!(loaded.anchors.len(), 1);
}

/// Something that is not a trusted list is refused rather than half-read.
#[test]
fn a_file_that_is_not_a_trusted_list_is_refused() {
    let error = openszigno_verify::trustlist::load(b"<hello/>", None, &RoxmltreeC14n)
        .expect_err("a bare element is not a trusted list");
    assert!(
        error.contains("not an ETSI TS 119 612 trusted list"),
        "{error}"
    );
}

// ---------------------------------------------------------------------------
// Service status over time
// ---------------------------------------------------------------------------

/// A service withdrawn *after* the validation time was still granted then, so
/// the chain is trusted and qualified at that instant.
#[test]
fn the_status_in_force_at_the_validation_time_decides() {
    let pki = pki((2019, 1, 1), &["0.4.0.1862.1.1"]);
    let mut service = TlService::ca_qc("openSzigno Test Qualified CA", pki.root_der.clone());
    service.status = STATUS_WITHDRAWN.to_owned();
    service.status_starting_time = "2021-01-01T00:00:00Z".to_owned();
    service.history = vec![
        (
            STATUS_UNDER_SUPERVISION.to_owned(),
            "2010-01-01T00:00:00Z".to_owned(),
        ),
        (STATUS_GRANTED.to_owned(), "2016-07-01T00:00:00Z".to_owned()),
    ];
    let list = build_trust_list(&TrustListSpec::new(vec![service]));
    let xml = dossier(signature(&pki), &pki.signer_key);

    // 2020: the granted history entry is the one in force.
    let report = run_with_list(&xml, &list, None, AT);
    assert_check(&report, CheckCode::CertificateQualified, CheckStatus::Info);
    assert_eq!(report.signatures[0].qualified, Some(true));
}

/// The same list, the same anchor, a later validation time: the service has
/// been withdrawn by then, so the chain is no longer qualified.
#[test]
fn a_withdrawn_service_is_not_qualified_afterwards() {
    let pki = pki((2019, 1, 1), &["0.4.0.1862.1.1"]);
    let mut service = TlService::ca_qc("openSzigno Test Qualified CA", pki.root_der.clone());
    service.status = STATUS_WITHDRAWN.to_owned();
    service.status_starting_time = "2021-01-01T00:00:00Z".to_owned();
    service.history = vec![(STATUS_GRANTED.to_owned(), "2016-07-01T00:00:00Z".to_owned())];
    let list = build_trust_list(&TrustListSpec::new(vec![service]));
    let xml = dossier(signature(&pki), &pki.signer_key);

    let report = run_with_list(&xml, &list, None, "2022-01-01T00:00:00Z");
    assert_check(
        &report,
        CheckCode::CertificateNotQualified,
        CheckStatus::Info,
    );
    assert_eq!(report.signatures[0].qualified, Some(false));
}

/// A pre-eIDAS status this build refuses to translate is not "granted", and
/// saying so is more honest than guessing which historical status meant what.
#[test]
fn a_pre_eidas_status_is_not_treated_as_granted() {
    let pki = pki((2014, 1, 1), &[]);
    let mut service = TlService::ca_qc("openSzigno Test Qualified CA", pki.root_der.clone());
    service.status = STATUS_UNDER_SUPERVISION.to_owned();
    service.status_starting_time = "2010-01-01T00:00:00Z".to_owned();
    let list = build_trust_list(&TrustListSpec::new(vec![service]));
    let xml = dossier(signature(&pki), &pki.signer_key);

    let report = run_with_list(&xml, &list, None, AT);
    assert_eq!(report.signatures[0].qualified, Some(false));
}

// ---------------------------------------------------------------------------
// Qualified determination
// ---------------------------------------------------------------------------

/// A post-eIDAS certificate must say so itself: the trusted list grants the
/// service, but a certificate with no `QcCompliance` is not a qualified one.
#[test]
fn a_post_eidas_certificate_without_qccompliance_is_not_qualified() {
    let pki = pki((2019, 1, 1), &[]);
    let list = build_trust_list(&TrustListSpec::new(vec![TlService::ca_qc(
        "openSzigno Test Qualified CA",
        pki.root_der.clone(),
    )]));
    let xml = dossier(signature(&pki), &pki.signer_key);
    let report = run_with_list(&xml, &list, None, AT);

    assert_check(
        &report,
        CheckCode::CertificateNotQualified,
        CheckStatus::Info,
    );
    assert_eq!(report.signatures[0].qualified, Some(false));
}

/// A pre-eIDAS certificate is judged on the trusted list alone, because the
/// statement had not been mandated when it was issued.
#[test]
fn a_pre_eidas_certificate_is_judged_on_the_list_alone() {
    let pki = pki((2014, 1, 1), &[]);
    let mut service = TlService::ca_qc("openSzigno Test Qualified CA", pki.root_der.clone());
    service.status_starting_time = "2010-01-01T00:00:00Z".to_owned();
    let list = build_trust_list(&TrustListSpec::new(vec![service]));
    let xml = dossier(signature(&pki), &pki.signer_key);
    let report = run_with_list(&xml, &list, None, AT);

    assert_eq!(report.signatures[0].qualified, Some(true));
}

/// `QcSSCD` is reported as the qualified-device claim it is.
#[test]
fn a_qscd_statement_is_reported() {
    let pki = pki((2019, 1, 1), &["0.4.0.1862.1.1", "0.4.0.1862.1.4"]);
    let list = build_trust_list(&TrustListSpec::new(vec![TlService::ca_qc(
        "openSzigno Test Qualified CA",
        pki.root_der.clone(),
    )]));
    let xml = dossier(signature(&pki), &pki.signer_key);
    let report = run_with_list(&xml, &list, None, AT);

    assert_eq!(report.signatures[0].qualified, Some(true));
    assert_eq!(report.signatures[0].qualified_signature_device, Some(true));
    assert_eq!(
        report.signatures[0]
            .signing_certificate
            .as_ref()
            .and_then(|summary| summary.qualified),
        Some(true)
    );
}

/// With no trusted list at all the answer is "not determined", which the report
/// keeps distinct from "determined not to be qualified".
#[test]
fn a_trust_store_anchor_leaves_qualified_undetermined() {
    let pki = pki((2019, 1, 1), &["0.4.0.1862.1.1"]);
    let trust = MemoryTrustStore::new(vec![pki.root_der.clone()], Vec::new());
    let revocation = MemoryRevocationStore::default();
    let backend = RoxmltreeC14n;
    let clock = FixedClock(parse_rfc3339(AT).expect("the fixed time parses"));
    let mut options = VerifyOptions::new(&clock, &trust, &revocation, &backend);
    options.requested_time = Some(AT.to_owned());
    let xml = dossier(signature(&pki), &pki.signer_key);
    let report = verify(xml.as_bytes(), &options).expect("the dossier parses");

    assert_check(
        &report,
        CheckCode::CertificateQualifiedUnknown,
        CheckStatus::Info,
    );
    assert_eq!(report.signatures[0].qualified, None);
}

// ---------------------------------------------------------------------------
// The list's own signature
// ---------------------------------------------------------------------------

/// Without a signer certificate the list is read but reported as unverified,
/// which is blocking: a list that could be anyone's cannot support `valid`.
#[test]
fn an_unverified_list_blocks_the_verdict() {
    let pki = pki((2019, 1, 1), &["0.4.0.1862.1.1"]);
    let list = build_trust_list(&TrustListSpec::new(vec![TlService::ca_qc(
        "openSzigno Test Qualified CA",
        pki.root_der.clone(),
    )]));
    let xml = dossier(signature(&pki), &pki.signer_key);
    let report = run_with_list(&xml, &list, None, AT);

    assert_check(
        &report,
        CheckCode::TrustListUnverified,
        CheckStatus::Unknown,
    );
    assert_eq!(report.verdict, openszigno_verify::Verdict::Indeterminate);
}

/// With the right signer certificate, the list's own XMLDSig signature
/// verifies through the same core the dossier pipeline uses.
#[test]
fn a_signed_list_verifies_against_its_signer() {
    let pki = pki((2019, 1, 1), &["0.4.0.1862.1.1"]);
    let mut spec = TrustListSpec::new(vec![TlService::ca_qc(
        "openSzigno Test Qualified CA",
        pki.root_der.clone(),
    )]);
    spec.signer = Some((rsa_key(keys::SECOND_RSA2048), pki.tl_signer_der.clone()));
    let list = build_trust_list(&spec);
    let xml = dossier(signature(&pki), &pki.signer_key);
    let report = run_with_list(&xml, &list, Some(&pki.tl_signer_der), AT);

    assert_check(
        &report,
        CheckCode::TrustListSignatureOk,
        CheckStatus::Passed,
    );
}

/// A list changed after it was signed does not verify, and the failure is a
/// failure rather than an "unknown".
#[test]
fn a_tampered_list_fails_its_signature_check() {
    let pki = pki((2019, 1, 1), &["0.4.0.1862.1.1"]);
    let mut spec = TrustListSpec::new(vec![TlService::ca_qc(
        "openSzigno Test Qualified CA",
        pki.root_der.clone(),
    )]);
    spec.signer = Some((rsa_key(keys::SECOND_RSA2048), pki.tl_signer_der.clone()));
    spec.tamper = true;
    let list = build_trust_list(&spec);
    let xml = dossier(signature(&pki), &pki.signer_key);
    let report = run_with_list(&xml, &list, Some(&pki.tl_signer_der), AT);

    assert_check(
        &report,
        CheckCode::TrustListSignatureInvalid,
        CheckStatus::Failed,
    );
    assert_eq!(report.verdict, openszigno_verify::Verdict::Invalid);
}

/// A list signed by one key and checked against another certificate does not
/// verify either.
#[test]
fn a_list_signed_by_the_wrong_key_fails() {
    let pki = pki((2019, 1, 1), &["0.4.0.1862.1.1"]);
    let mut spec = TrustListSpec::new(vec![TlService::ca_qc(
        "openSzigno Test Qualified CA",
        pki.root_der.clone(),
    )]);
    // Signed with a third key, checked against the declared signer's
    // certificate.
    spec.signer = Some((rsa_key(keys::THIRD_RSA2048), pki.tl_signer_der.clone()));
    let list = build_trust_list(&spec);
    let xml = dossier(signature(&pki), &pki.signer_key);
    let report = run_with_list(&xml, &list, Some(&pki.tl_signer_der), AT);

    assert_check(
        &report,
        CheckCode::TrustListSignatureInvalid,
        CheckStatus::Failed,
    );
}

/// A list that carries no signature at all, checked against a signer, is a
/// failure and not a silent pass.
#[test]
fn a_list_with_no_signature_fails_when_one_is_demanded() {
    let pki = pki((2019, 1, 1), &["0.4.0.1862.1.1"]);
    let list = build_trust_list(&TrustListSpec::new(vec![TlService::ca_qc(
        "openSzigno Test Qualified CA",
        pki.root_der.clone(),
    )]));
    let loaded = openszigno_verify::trustlist::load(
        list.as_bytes(),
        Some(&pki.tl_signer_der),
        &RoxmltreeC14n,
    )
    .expect("the list still loads");
    assert!(
        loaded
            .checks
            .iter()
            .any(|check| check.code == CheckCode::TrustListSignatureInvalid),
        "an unsigned list must not pass a signature check that was demanded"
    );
}

// ---------------------------------------------------------------------------
// The list signature's own structural rules
// ---------------------------------------------------------------------------

/// A signed list, edited so that one part of its `ds:Signature` is wrong. Every
/// case below must be refused *before* the signature itself is checked, so a
/// caller learns which rule the list broke rather than only that a signature
/// did not verify.
fn signed_list(pki: &Pki) -> String {
    let mut spec = TrustListSpec::new(vec![TlService::ca_qc(
        "openSzigno Test Qualified CA",
        pki.root_der.clone(),
    )]);
    spec.signer = Some((rsa_key(keys::SECOND_RSA2048), pki.tl_signer_der.clone()));
    build_trust_list(&spec)
}

fn signature_check(list: &str, signer: &[u8]) -> openszigno_verify::codes::Check {
    let loaded = openszigno_verify::trustlist::load(list.as_bytes(), Some(signer), &RoxmltreeC14n)
        .expect("the list still parses");
    loaded
        .checks
        .into_iter()
        .find(|check| {
            matches!(
                check.code,
                CheckCode::TrustListSignatureOk | CheckCode::TrustListSignatureInvalid
            )
        })
        .expect("a signature check is always emitted when a signer is given")
}

#[test]
fn the_list_signature_rules_are_each_reported() {
    let pki = pki((2019, 1, 1), &[]);
    let list = signed_list(&pki);

    for (edited, expected) in [
        (
            list.replace("<ds:SignedInfo>", "<ds:SignedInfoX>")
                .replace("</ds:SignedInfo>", "</ds:SignedInfoX>"),
            "has no ds:SignedInfo",
        ),
        (
            list.replace("<ds:SignatureValue>", "<ds:SignatureValueX>")
                .replace("</ds:SignatureValue>", "</ds:SignatureValueX>"),
            "has no ds:SignatureValue",
        ),
        (
            list.replace(
                "Algorithm=\"http://www.w3.org/2001/10/xml-exc-c14n#\"/><ds:SignatureMethod",
                "Algorithm=\"http://www.w3.org/2006/12/xml-c14n11\"/><ds:SignatureMethod",
            ),
            "canonicalization method outside the allowlist",
        ),
        (
            list.replace(
                "http://www.w3.org/2001/04/xmldsig-more#rsa-sha256",
                "http://www.w3.org/2000/09/xmldsig#rsa-sha1",
            ),
            "signature method outside the allowlist",
        ),
        (
            list.replace("<ds:Reference URI=\"\">", "<ds:ReferenceX URI=\"\">")
                .replace("</ds:Reference>", "</ds:ReferenceX>"),
            "carries no ds:Reference",
        ),
        (
            list.replace(
                "Algorithm=\"http://www.w3.org/2001/10/xml-exc-c14n#\"/></ds:Transforms>",
                "Algorithm=\"http://www.w3.org/TR/1999/REC-xslt-19991116\"/></ds:Transforms>",
            ),
            "transform outside the allowlist",
        ),
        (
            list.replace(
                "<ds:DigestMethod Algorithm=\"http://www.w3.org/2001/04/xmlenc#sha256\"/>",
                "<ds:DigestMethod Algorithm=\"http://www.w3.org/2000/09/xmldsig#sha1\"/>",
            ),
            "digest outside the allowlist",
        ),
    ] {
        let check = signature_check(&edited, &pki.tl_signer_der);
        assert_eq!(check.code, CheckCode::TrustListSignatureInvalid);
        assert!(check.message.contains(expected), "{}", check.message);
    }
}

/// A reference that covers only part of the list leaves the service entries
/// unprotected, and is refused for that reason and not for a digest mismatch.
#[test]
fn a_signature_that_covers_only_part_of_the_list_is_refused() {
    let pki = pki((2019, 1, 1), &[]);
    // Two signatures is one of the shapes a partial-coverage attack takes, and
    // is refused before anything else is looked at.
    let list = signed_list(&pki);
    let doubled = list.replace(
        "</tsl:TrustServiceProviderList>",
        "</tsl:TrustServiceProviderList><ds:Signature xmlns:ds=\"http://www.w3.org/2000/09/xmldsig#\" Id=\"decoy\"/>",
    );
    let check = signature_check(&doubled, &pki.tl_signer_der);
    assert_eq!(check.code, CheckCode::TrustListSignatureInvalid);
    assert!(
        check.message.contains("exactly one ds:Signature"),
        "{}",
        check.message
    );
}

/// A `--trust-list-signer` file that is not a certificate is refused, rather
/// than being read as "no signer was given".
#[test]
fn a_signer_that_is_not_a_certificate_is_refused() {
    let pki = pki((2019, 1, 1), &[]);
    let check = signature_check(&signed_list(&pki), b"not a certificate");
    assert_eq!(check.code, CheckCode::TrustListSignatureInvalid);
    assert!(
        check.message.contains("not a usable X.509 certificate"),
        "{}",
        check.message
    );
}

/// A `ds:SignatureValue` that is not Base64 is a malformed signature, not an
/// unverifiable one.
#[test]
fn a_signature_value_that_is_not_base64_is_refused() {
    let pki = pki((2019, 1, 1), &[]);
    let list = signed_list(&pki);
    let start = list
        .find("<ds:SignatureValue>")
        .expect("the element exists")
        + "<ds:SignatureValue>".len();
    let end = list
        .find("</ds:SignatureValue>")
        .expect("the element exists");
    let edited = format!("{}not base64!!{}", &list[..start], &list[end..]);
    let check = signature_check(&edited, &pki.tl_signer_der);
    assert_eq!(check.code, CheckCode::TrustListSignatureInvalid);
    assert!(check.message.contains("not Base64"), "{}", check.message);
}

/// The service-type names are stable strings.
#[test]
fn service_type_names_are_stable() {
    use openszigno_verify::ServiceType;
    assert_eq!(ServiceType::CaQc.as_str(), "ca_qc");
    assert_eq!(ServiceType::TsaQtst.as_str(), "tsa_qtst");
}
