//! Where a certification path may **end** once a trusted list is loaded.
//!
//! ETSI TS 119 615 puts the trust anchor where the list speaks, which in a
//! real national list is the *issuing* CA rather than the self-signed root
//! above it. The Hungarian list is the worked example: NetLock's qualified
//! issuing CAs carry the CA/QC entries, with pre-eIDAS history, while the root
//! that signed them is recorded only as a qualified timestamping service
//! granted years later. A path that had to climb to the root would be judged
//! by a statement that was never about issuing certificates.
//!
//! Every list here is generated by the test helper, and every certificate by
//! the synthetic PKI. The real lists in `refs/trust` are read only as
//! documentation of the schema, never by the suite.

mod common;

use common::{
    CertSpec, DossierSpec, STATUS_GRANTED, STATUS_UNDER_SUPERVISION, SVCTYPE_TSA_QTST, SigSpec,
    SigningCertificateSpec, TestKey, TimestampSpec, TlService, TrustListSpec, build,
    document_signature, extended_key_usage_extension, issued_by, keys, qc_statements_extension,
    rsa_key, self_signed,
};
use openszigno_verify::codes::{CheckCode, CheckStatus};
use openszigno_verify::{
    FixedClock, MemoryRevocationStore, MemoryTrustStore, RoxmltreeC14n, TrustAnchorOrigin, Verdict,
    VerifyOptions, VerifyReport, parse_rfc3339, verify,
};
use rcgen::BasicConstraints;

const ID_KP_TIME_STAMPING: &str = "1.3.6.1.5.5.7.3.8";
const CA_NAME: &str = "Qualified openSzigno CA 2009";

/// A root, the issuing CA the list names, a signer, and a timestamp authority
/// under that same issuing CA. Every certificate is valid from 2003 to 2039,
/// so that the *only* thing a validation time can change is what the trusted
/// list says.
struct Pki {
    root_der: Vec<u8>,
    intermediate_der: Vec<u8>,
    signer_der: Vec<u8>,
    signer_key: TestKey,
    tsa_der: Vec<u8>,
}

fn pki() -> Pki {
    let root_key = rsa_key(keys::ROOT_RSA2048);
    let intermediate_key = rsa_key(keys::INTERMEDIATE_RSA2048);
    let signer_key = rsa_key(keys::SIGNER_RSA2048);

    let mut root_spec = CertSpec::ca("openSzigno Test Root", BasicConstraints::Unconstrained);
    root_spec.not_before = (2003, 1, 1);
    let root = self_signed(&root_spec, &root_key);

    let mut intermediate_spec = CertSpec::ca(CA_NAME, BasicConstraints::Constrained(0));
    intermediate_spec.not_before = (2003, 1, 1);
    let intermediate = issued_by(&intermediate_spec, &intermediate_key, &root, &root_key);

    let mut signer_spec = CertSpec::signer("openSzigno Test Signer");
    signer_spec.not_before = (2003, 1, 1);
    signer_spec.custom_extensions = vec![qc_statements_extension(&["0.4.0.1862.1.1"])];
    let signer = issued_by(&signer_spec, &signer_key, &intermediate, &intermediate_key);

    let mut tsa_spec = CertSpec::signer("openSzigno Test TSA");
    tsa_spec.not_before = (2003, 1, 1);
    tsa_spec.custom_extensions = vec![extended_key_usage_extension(&[ID_KP_TIME_STAMPING], true)];
    let tsa = issued_by(
        &tsa_spec,
        &rsa_key(keys::THIRD_RSA2048),
        &intermediate,
        &intermediate_key,
    );

    Pki {
        root_der: root.der,
        intermediate_der: intermediate.der,
        signer_der: signer.der,
        signer_key,
        tsa_der: tsa.der,
    }
}

/// The dossier every test here verifies: the signer, with the issuing CA in
/// `xades:CertificateValues` and no root anywhere, which is the shape a real
/// dossier has.
fn signature(pki: &Pki) -> SigSpec {
    let mut signature = document_signature(vec![pki.signer_der.clone()]);
    signature.signing_certificate = Some(SigningCertificateSpec::v1(pki.signer_der.clone()));
    signature.certificate_values = vec![pki.intermediate_der.clone()];
    signature
}

fn dossier(pki: &Pki, signature: SigSpec) -> String {
    let spec = DossierSpec {
        document_signature: Some(signature),
        ..Default::default()
    };
    build(&spec, &[("doc", &pki.signer_key)])
}

/// The issuing CA as the Hungarian list records one: supervised from 2005 under
/// the pre-eIDAS vocabulary, granted under eIDAS from 2016-06-30.
fn issuing_ca_service(pki: &Pki) -> TlService {
    let mut service = TlService::ca_qc(CA_NAME, pki.intermediate_der.clone());
    service.status = STATUS_GRANTED.to_owned();
    service.status_starting_time = "2016-06-30T00:00:00Z".to_owned();
    service.history = vec![(
        STATUS_UNDER_SUPERVISION.to_owned(),
        "2005-01-01T00:00:00Z".to_owned(),
    )];
    service
}

/// The root as the Hungarian list records the NetLock Arany one: a qualified
/// timestamping service granted from 2018, with no history and nothing said
/// about issuing certificates.
fn qtst_only_root_service(pki: &Pki) -> TlService {
    let mut service = TlService::ca_qc("openSzigno Test Root QTSA", pki.root_der.clone());
    service.service_type = SVCTYPE_TSA_QTST.to_owned();
    service.status = STATUS_GRANTED.to_owned();
    service.status_starting_time = "2018-01-01T00:00:00Z".to_owned();
    service
}

/// Verify against a trusted list and nothing else: no `--trust-store`, so the
/// only trust in the run is what the list supplies.
fn run(xml: &str, list: &str, time: &str) -> VerifyReport {
    let backend = RoxmltreeC14n;
    let loaded = openszigno_verify::trustlist::load(list.as_bytes(), &[], &backend)
        .expect("the synthetic trusted list loads");
    let mut trust = MemoryTrustStore::default();
    for check in loaded.checks {
        trust.push_check(check);
    }
    trust.extend_anchors(loaded.anchors);
    trust.extend_services(loaded.service_identities);

    let revocation = MemoryRevocationStore::default();
    let clock = FixedClock(parse_rfc3339(time).expect("the fixed time parses"));
    let mut options = VerifyOptions::new(&clock, &trust, &revocation, &backend);
    options.requested_time = Some(time.to_owned());
    verify(xml.as_bytes(), &options).expect("the dossier parses structurally")
}

fn codes(report: &VerifyReport) -> Vec<String> {
    report
        .checks
        .iter()
        .chain(report.signatures.iter().flat_map(|signature| {
            signature.checks.iter().chain(
                signature
                    .timestamps
                    .iter()
                    .flat_map(|timestamp| timestamp.checks.iter()),
            )
        }))
        .map(|check| format!("{}={}", check.code.as_str(), check.status.as_str()))
        .collect()
}

fn assert_check(report: &VerifyReport, code: CheckCode, status: CheckStatus) {
    let seen = codes(report);
    assert!(
        seen.contains(&format!("{}={}", code.as_str(), status.as_str())),
        "expected {}={}; got {seen:?}",
        code.as_str(),
        status.as_str()
    );
}

fn assert_absent(report: &VerifyReport, code: CheckCode) {
    let seen = codes(report);
    assert!(
        !seen
            .iter()
            .any(|entry| entry.starts_with(&format!("{}=", code.as_str()))),
        "expected no {}; got {seen:?}",
        code.as_str()
    );
}

/// The path ends at the issuing CA and is reported as ending there.
fn assert_anchored_at_the_issuing_ca(report: &VerifyReport, pki: &Pki) {
    let chain = &report.signatures[0].chain;
    assert_eq!(chain.len(), 2, "the signer and the issuing CA, and no root");
    let anchor = chain.last().expect("the chain ends at an anchor");
    assert!(anchor.is_trust_anchor);
    assert_eq!(anchor.der, pki.intermediate_der);
    assert_eq!(
        anchor.trust_anchor_origin,
        Some(TrustAnchorOrigin::TrustList)
    );
}

// ---------------------------------------------------------------------------
// A listed issuing CA ends the path
// ---------------------------------------------------------------------------

/// The list names only the issuing CA and the root is absent from it and from
/// any store. The path ends at the issuing CA at both a pre-eIDAS validation
/// time, where the supervised status counts, and a post-eIDAS one, where the
/// granted status does.
#[test]
fn a_listed_issuing_ca_ends_the_path_at_both_eras() {
    let pki = pki();
    let list = build_list(vec![issuing_ca_service(&pki)]);
    let xml = dossier(&pki, signature(&pki));

    for time in ["2014-06-01T00:00:00Z", "2020-06-01T00:00:00Z"] {
        let report = run(&xml, &list, time);
        assert_check(&report, CheckCode::CertPathOk, CheckStatus::Passed);
        assert_absent(&report, CheckCode::TrustListServiceNotGranted);
        assert_check(&report, CheckCode::CertificateQualified, CheckStatus::Info);
        assert_eq!(report.signatures[0].qualified, Some(true), "at {time}");
        assert_eq!(
            report.signatures[0].qualified_service.as_deref(),
            Some(CA_NAME)
        );
        assert_anchored_at_the_issuing_ca(&report, &pki);
    }
}

/// Before the list said anything about the issuing CA there is no trust to end
/// a path with, and nothing above it is listed either. The refusal is
/// `unknown` — missing trust is not evidence against a signature — so the run
/// is capped at `indeterminate` rather than pushed to `invalid`.
#[test]
fn a_listed_issuing_ca_refuses_the_path_before_it_was_granted() {
    let pki = pki();
    let list = build_list(vec![issuing_ca_service(&pki)]);
    let report = run(
        &dossier(&pki, signature(&pki)),
        &list,
        "2004-01-01T00:00:00Z",
    );

    assert_absent(&report, CheckCode::CertPathOk);
    assert_check(
        &report,
        CheckCode::TrustListServiceNotGranted,
        CheckStatus::Unknown,
    );
    assert_eq!(report.verdict, Verdict::Indeterminate);
    assert_eq!(report.signatures[0].qualified, Some(false));
}

/// The regression this exists for. The root is listed too, but only as a
/// qualified timestamping service granted from 2018, exactly as the Hungarian
/// list records the NetLock Arany root. A 2014 signer must be judged by the
/// issuing CA's CA/QC entry, which was supervised then, and not by an entry
/// about timestamping that had not started.
#[test]
fn a_qtst_only_root_entry_does_not_override_the_issuing_ca() {
    let pki = pki();
    let list = build_list(vec![issuing_ca_service(&pki), qtst_only_root_service(&pki)]);
    let report = run(
        &dossier(&pki, signature(&pki)),
        &list,
        "2014-06-01T00:00:00Z",
    );

    assert_check(&report, CheckCode::CertPathOk, CheckStatus::Passed);
    assert_absent(&report, CheckCode::TrustListServiceNotGranted);
    assert_eq!(report.signatures[0].qualified, Some(true));
    // The root is a self-signed listed anchor and a perfectly good path leads
    // to it, but the nearer listed service is the one that decides.
    assert_anchored_at_the_issuing_ca(&report, &pki);
}

/// The `--online` fetcher may contact a URL only for a certificate on a path
/// this run validated. A path that ends at a listed intermediate is such a
/// path, and both of its certificates are in the set — while the root, which
/// no validated path reached, is not.
#[test]
fn the_online_fetch_planner_sees_a_path_that_ends_at_a_listed_intermediate() {
    let pki = pki();
    let list = build_list(vec![issuing_ca_service(&pki), qtst_only_root_service(&pki)]);
    let report = run(
        &dossier(&pki, signature(&pki)),
        &list,
        "2014-06-01T00:00:00Z",
    );

    let certificates = report.validated_path_certificates();
    assert!(certificates.contains(&pki.signer_der));
    assert!(certificates.contains(&pki.intermediate_der));
    assert!(!certificates.contains(&pki.root_der));
}

// ---------------------------------------------------------------------------
// Timestamping under the same issuing CA
// ---------------------------------------------------------------------------

/// A signature carrying a timestamp whose authority sits under the listed
/// issuing CA, with the CA in the token so the path can be built.
fn signature_with_timestamp(pki: &Pki, gen_time: &str) -> SigSpec {
    let mut signature = signature(pki);
    let mut timestamp =
        TimestampSpec::new(rsa_key(keys::THIRD_RSA2048), pki.tsa_der.clone(), gen_time);
    timestamp.token_certificates = vec![pki.intermediate_der.clone()];
    signature.timestamp = Some(timestamp);
    signature
}

/// The list says nothing about timestamping for the issuing CA, so it has not
/// refused this use, and the CA/QC service it *does* record was granted then:
/// the LAB-307 softening lets the TSA's path end there.
#[test]
fn a_tsa_under_a_listed_issuing_ca_relies_on_the_ca_qc_softening() {
    let pki = pki();
    let list = build_list(vec![issuing_ca_service(&pki)]);
    let xml = dossier(&pki, signature_with_timestamp(&pki, "2014-06-01T00:00:00Z"));
    let report = run(&xml, &list, "2014-06-01T00:00:00Z");

    assert_check(&report, CheckCode::TimestampTsaPathOk, CheckStatus::Passed);
}

/// Once the list *does* record a TSA/QTST service for that issuing CA, the
/// softening no longer applies: the list has spoken about timestamping, and
/// what it says at this instant is that the service had not started.
#[test]
fn a_tsa_qtst_entry_that_had_not_started_refuses_the_timestamp_path() {
    let pki = pki();
    let mut qtst = TlService::ca_qc("openSzigno Test QTSA", pki.intermediate_der.clone());
    qtst.service_type = SVCTYPE_TSA_QTST.to_owned();
    qtst.status = STATUS_GRANTED.to_owned();
    qtst.status_starting_time = "2018-01-01T00:00:00Z".to_owned();
    let list = build_list(vec![issuing_ca_service(&pki), qtst]);
    let xml = dossier(&pki, signature_with_timestamp(&pki, "2014-06-01T00:00:00Z"));
    let report = run(&xml, &list, "2014-06-01T00:00:00Z");

    assert_absent(&report, CheckCode::TimestampTsaPathOk);
    assert_check(
        &report,
        CheckCode::TrustListServiceNotGranted,
        CheckStatus::Unknown,
    );
    // The signer's own path is unaffected: the CA/QC entry decides that one.
    assert_check(&report, CheckCode::CertPathOk, CheckStatus::Passed);
}

fn build_list(services: Vec<TlService>) -> String {
    common::build_trust_list(&TrustListSpec::new(services))
}
