//! ETSI TS 119 612 trusted lists: anchor loading, service status over time,
//! qualified determination, and the list's own signature.
//!
//! Every list here is generated by the test helper. The real EU and Hungarian
//! lists in `refs/trust` are read only as documentation of the schema, never by
//! the suite: they change daily, and asserting anything about a real trust
//! service provider would make this suite a statement about that provider.

mod common;

use common::{
    CertSpec, DossierSpec, STATUS_ACCREDITED, STATUS_GRANTED, STATUS_UNDER_SUPERVISION,
    STATUS_WITHDRAWN, SVCTYPE_TSA_QTST, SigSpec, SigningCertificateSpec, TestKey, TlService,
    TrustListSpec, build, build_trust_list, document_signature, issued_by, keys,
    qc_statements_extension, rsa_key, self_signed,
};
use openszigno_verify::certs::{CertificateSource, ParsedCertificate};
use openszigno_verify::codes::{CheckCode, CheckStatus};
use openszigno_verify::{
    FixedClock, MemoryRevocationStore, MemoryTrustStore, RoxmltreeC14n, TrustAnchorOrigin, Verdict,
    VerifyOptions, VerifyReport, parse_rfc3339, verify,
};
use rcgen::BasicConstraints;

const AT: &str = "2020-06-02T00:00:00Z";

struct Pki {
    root_der: Vec<u8>,
    signer_der: Vec<u8>,
    signer_key: TestKey,
    tl_signer_der: Vec<u8>,
}

/// `not_before` decides whether the signing certificate is treated as
/// post-eIDAS, and `qc` decides which QCStatements it asserts.
fn pki(not_before: (i32, u8, u8), qc: &[&str]) -> Pki {
    let root_key = rsa_key(keys::ROOT_RSA2048);
    let signer_key = rsa_key(keys::SIGNER_RSA2048);

    let root = self_signed(
        &CertSpec::ca(
            "openSzigno Test Qualified CA",
            BasicConstraints::Unconstrained,
        ),
        &root_key,
    );
    let mut signer_spec = CertSpec::signer("openSzigno Test Signer");
    signer_spec.not_before = not_before;
    if !qc.is_empty() {
        signer_spec.custom_extensions = vec![qc_statements_extension(qc)];
    }
    let signer = issued_by(&signer_spec, &signer_key, &root, &root_key);
    let tl_signer = self_signed(
        &CertSpec::signer("openSzigno Test Trusted List Signer"),
        &rsa_key(keys::SECOND_RSA2048),
    );

    Pki {
        root_der: root.der,
        signer_der: signer.der,
        signer_key,
        tl_signer_der: tl_signer.der,
    }
}

fn signature(pki: &Pki) -> SigSpec {
    let mut signature = document_signature(vec![pki.signer_der.clone()]);
    signature.signing_certificate = Some(SigningCertificateSpec::v1(pki.signer_der.clone()));
    signature
}

fn dossier(signature: SigSpec, key: &TestKey) -> String {
    let spec = DossierSpec {
        document_signature: Some(signature),
        ..Default::default()
    };
    build(&spec, &[("doc", key)])
}

/// Load one trusted list and verify a dossier against the anchors it yields.
fn run_with_list(xml: &str, list: &str, signer: Option<&[u8]>, time: &str) -> VerifyReport {
    let signers: Vec<Vec<u8>> = signer.map(<[u8]>::to_vec).into_iter().collect();
    let backend = RoxmltreeC14n;
    let loaded = openszigno_verify::trustlist::load(list.as_bytes(), &signers, &backend)
        .expect("the synthetic trusted list loads");
    let mut trust = MemoryTrustStore::default();
    for check in loaded.checks {
        trust.push_check(check);
    }
    trust.extend_anchors(loaded.anchors);
    trust.extend_services(loaded.service_identities);

    let revocation = MemoryRevocationStore::default();
    let clock = FixedClock(parse_rfc3339(time).expect("the fixed time parses"));
    let mut options = VerifyOptions::new(&clock, &trust, &revocation, &backend);
    options.requested_time = Some(time.to_owned());
    verify(xml.as_bytes(), &options).expect("the dossier parses structurally")
}

fn codes(report: &VerifyReport) -> Vec<String> {
    report
        .checks
        .iter()
        .chain(
            report
                .signatures
                .iter()
                .flat_map(|signature| signature.checks.iter()),
        )
        .map(|check| format!("{}={}", check.code.as_str(), check.status.as_str()))
        .collect()
}

fn assert_check(report: &VerifyReport, code: CheckCode, status: CheckStatus) {
    let seen = codes(report);
    assert!(
        seen.contains(&format!("{}={}", code.as_str(), status.as_str())),
        "expected {}={}; got {seen:?}",
        code.as_str(),
        status.as_str()
    );
}

// ---------------------------------------------------------------------------
// Loading
// ---------------------------------------------------------------------------

/// A granted CA/QC service contributes its digital identity as a trust anchor,
/// and the report says the anchor came from a trusted list rather than from a
/// directory somebody filled in.
#[test]
fn a_granted_ca_qc_service_supplies_an_anchor() {
    let pki = pki((2019, 1, 1), &["0.4.0.1862.1.1"]);
    let list = build_trust_list(&TrustListSpec::new(vec![TlService::ca_qc(
        "openSzigno Test Qualified CA",
        pki.root_der.clone(),
    )]));
    let xml = dossier(signature(&pki), &pki.signer_key);
    let report = run_with_list(&xml, &list, None, AT);

    assert_check(&report, CheckCode::CertPathOk, CheckStatus::Passed);
    assert_check(&report, CheckCode::TrustListLoaded, CheckStatus::Info);
    let anchor = report.signatures[0]
        .chain
        .last()
        .expect("the chain ends at an anchor");
    assert!(anchor.is_trust_anchor);
    assert_eq!(
        anchor.trust_anchor_origin,
        Some(TrustAnchorOrigin::TrustList)
    );
}

/// The list's metadata is read, so a result can cite exactly which snapshot it
/// relied on.
#[test]
fn the_list_metadata_is_read() {
    let pki = pki((2019, 1, 1), &[]);
    let list = build_trust_list(&TrustListSpec::new(vec![TlService::ca_qc(
        "openSzigno Test Qualified CA",
        pki.root_der.clone(),
    )]));
    let loaded = openszigno_verify::trustlist::load(list.as_bytes(), &[], &RoxmltreeC14n)
        .expect("the list loads");
    assert_eq!(loaded.territory.as_deref(), Some("HU"));
    assert_eq!(loaded.sequence_number, Some(7));
    assert_eq!(loaded.issue_date.as_deref(), Some("2020-01-01T00:00:00Z"));
    assert_eq!(loaded.next_update.as_deref(), Some("2021-01-01T00:00:00Z"));
    assert_eq!(loaded.anchors.len(), 1);
}

/// A `DigitalId` that only names a subject supplies no certificate, so it
/// supplies no anchor. The verifier will not go looking for one.
#[test]
fn a_digital_id_without_a_certificate_supplies_no_anchor() {
    let mut service = TlService::ca_qc("named only", Vec::new());
    service.certificates = Vec::new();
    service.subject_name_only = true;
    let list = build_trust_list(&TrustListSpec::new(vec![service]));
    let loaded = openszigno_verify::trustlist::load(list.as_bytes(), &[], &RoxmltreeC14n)
        .expect("the list loads");
    assert!(loaded.anchors.is_empty());
}

/// A service of a type this build does not read — a qualified timestamping
/// authority is read, but nothing else is — contributes nothing.
#[test]
fn a_tsa_qtst_service_is_also_read() {
    let pki = pki((2019, 1, 1), &[]);
    let mut service = TlService::ca_qc("openSzigno Test QTSA", pki.root_der.clone());
    service.service_type = SVCTYPE_TSA_QTST.to_owned();
    let list = build_trust_list(&TrustListSpec::new(vec![service]));
    let loaded = openszigno_verify::trustlist::load(list.as_bytes(), &[], &RoxmltreeC14n)
        .expect("the list loads");
    assert_eq!(loaded.anchors.len(), 1);
}

/// Something that is not a trusted list is refused rather than half-read.
#[test]
fn a_file_that_is_not_a_trusted_list_is_refused() {
    let error = openszigno_verify::trustlist::load(b"<hello/>", &[], &RoxmltreeC14n)
        .expect_err("a bare element is not a trusted list");
    assert!(
        error.contains("not an ETSI TS 119 612 trusted list"),
        "{error}"
    );
}

fn assert_absent(report: &VerifyReport, code: CheckCode) {
    let seen = codes(report);
    assert!(
        !seen
            .iter()
            .any(|entry| entry.starts_with(&format!("{}=", code.as_str()))),
        "expected no {}; got {seen:?}",
        code.as_str()
    );
}

// ---------------------------------------------------------------------------
// Service status over time
// ---------------------------------------------------------------------------

/// A service withdrawn *after* the validation time was still granted then, so
/// the chain is trusted and qualified at that instant.
#[test]
fn the_status_in_force_at_the_validation_time_decides() {
    let pki = pki((2019, 1, 1), &["0.4.0.1862.1.1"]);
    let mut service = TlService::ca_qc("openSzigno Test Qualified CA", pki.root_der.clone());
    service.status = STATUS_WITHDRAWN.to_owned();
    service.status_starting_time = "2021-01-01T00:00:00Z".to_owned();
    service.history = vec![
        (
            STATUS_UNDER_SUPERVISION.to_owned(),
            "2010-01-01T00:00:00Z".to_owned(),
        ),
        (STATUS_GRANTED.to_owned(), "2016-07-01T00:00:00Z".to_owned()),
    ];
    let list = build_trust_list(&TrustListSpec::new(vec![service]));
    let xml = dossier(signature(&pki), &pki.signer_key);

    // 2020: the granted history entry is the one in force, so the anchor may
    // end the path and the chain is qualified.
    let report = run_with_list(&xml, &list, None, AT);
    assert_check(&report, CheckCode::CertPathOk, CheckStatus::Passed);
    assert_absent(&report, CheckCode::TrustListServiceNotGranted);
    assert_check(&report, CheckCode::CertificateQualified, CheckStatus::Info);
    assert_eq!(report.signatures[0].qualified, Some(true));
}

/// A service granted at the validation time anchors the path, which is the
/// other half of the rule below: the status timeline decides both ways.
#[test]
fn a_granted_service_still_anchors_the_path() {
    let pki = pki((2019, 1, 1), &["0.4.0.1862.1.1"]);
    let mut service = TlService::ca_qc("openSzigno Test Qualified CA", pki.root_der.clone());
    service.status = STATUS_GRANTED.to_owned();
    service.status_starting_time = "2016-07-01T00:00:00Z".to_owned();
    let list = build_trust_list(&TrustListSpec::new(vec![service]));
    let xml = dossier(signature(&pki), &pki.signer_key);

    let report = run_with_list(&xml, &list, None, AT);
    assert_check(&report, CheckCode::CertPathOk, CheckStatus::Passed);
    assert_absent(&report, CheckCode::TrustListServiceNotGranted);
}

/// The same list, the same anchor, a later validation time: the service has
/// been withdrawn by then, so the chain is no longer qualified.
#[test]
fn a_withdrawn_service_is_not_qualified_afterwards() {
    let pki = pki((2019, 1, 1), &["0.4.0.1862.1.1"]);
    let mut service = TlService::ca_qc("openSzigno Test Qualified CA", pki.root_der.clone());
    service.status = STATUS_WITHDRAWN.to_owned();
    service.status_starting_time = "2021-01-01T00:00:00Z".to_owned();
    service.history = vec![(STATUS_GRANTED.to_owned(), "2016-07-01T00:00:00Z".to_owned())];
    let list = build_trust_list(&TrustListSpec::new(vec![service]));
    let xml = dossier(signature(&pki), &pki.signer_key);

    let report = run_with_list(&xml, &list, None, "2022-01-01T00:00:00Z");
    assert_check(
        &report,
        CheckCode::CertificateNotQualified,
        CheckStatus::Info,
    );
    assert_eq!(report.signatures[0].qualified, Some(false));

    // The withdrawal reaches the path itself, not only the qualified flag: an
    // anchor the list has stopped vouching for cannot end a path at an instant
    // it was not granted at. It is `unknown`, not `failed` — the trust is
    // missing, which is not evidence against the signature — so the run is
    // capped at `indeterminate` rather than pushed to `invalid`.
    assert_absent(&report, CheckCode::CertPathOk);
    assert_check(
        &report,
        CheckCode::TrustListServiceNotGranted,
        CheckStatus::Unknown,
    );
    assert_eq!(report.verdict, Verdict::Indeterminate);
}

/// The list must still be vouching for the certificate, whichever kind of
/// service it named it under: a root the list records only as a withdrawn
/// timestamping authority anchors nothing, not even a signing path.
#[test]
fn an_anchor_whose_every_service_is_withdrawn_anchors_nothing() {
    let pki = pki((2019, 1, 1), &["0.4.0.1862.1.1"]);
    let mut service = TlService::ca_qc("openSzigno Test Qualified CA", pki.root_der.clone());
    service.service_type = SVCTYPE_TSA_QTST.to_owned();
    service.status = STATUS_WITHDRAWN.to_owned();
    service.status_starting_time = "2018-01-01T00:00:00Z".to_owned();
    let list = build_trust_list(&TrustListSpec::new(vec![service]));
    let xml = dossier(signature(&pki), &pki.signer_key);

    let report = run_with_list(&xml, &list, None, AT);
    assert_absent(&report, CheckCode::CertPathOk);
    assert_check(
        &report,
        CheckCode::TrustListServiceNotGranted,
        CheckStatus::Unknown,
    );
}

/// A pre-eIDAS status this build refuses to translate is not "granted", and
/// saying so is more honest than guessing which historical status meant what.
#[test]
fn a_pre_eidas_status_is_not_granted_after_eidas_applied() {
    let pki = pki((2014, 1, 1), &[]);
    let mut service = TlService::ca_qc("openSzigno Test Qualified CA", pki.root_der.clone());
    service.status = STATUS_UNDER_SUPERVISION.to_owned();
    service.status_starting_time = "2010-01-01T00:00:00Z".to_owned();
    let list = build_trust_list(&TrustListSpec::new(vec![service]));
    let xml = dossier(signature(&pki), &pki.signer_key);

    let report = run_with_list(&xml, &list, None, AT);
    assert_eq!(report.signatures[0].qualified, Some(false));
}

// ---------------------------------------------------------------------------
// Qualified determination
// ---------------------------------------------------------------------------

/// A post-eIDAS certificate whose `QCStatements` are present but omit
/// `QcCompliance` contradicts the list, and the contradiction wins.
#[test]
fn a_post_eidas_certificate_that_contradicts_the_list_is_not_qualified() {
    // `id-etsi-qcs-QcRetentionPeriod`: a statement, but not the one that says
    // "this is a qualified certificate".
    let pki = pki((2019, 1, 1), &["0.4.0.1862.1.3"]);
    let list = build_trust_list(&TrustListSpec::new(vec![TlService::ca_qc(
        "openSzigno Test Qualified CA",
        pki.root_der.clone(),
    )]));
    let xml = dossier(signature(&pki), &pki.signer_key);
    let report = run_with_list(&xml, &list, None, AT);

    assert_check(
        &report,
        CheckCode::CertificateNotQualified,
        CheckStatus::Info,
    );
    assert_eq!(report.signatures[0].qualified, Some(false));
}

/// A post-eIDAS certificate carrying **no** `QCStatements` extension at all
/// denies nothing, so the trusted list remains the authority. This is the
/// looser of the two readings, taken deliberately: an issuer that omitted an
/// assertion has not contradicted the member state that listed it.
#[test]
fn a_post_eidas_certificate_with_no_statements_rests_on_the_list() {
    let pki = pki((2019, 1, 1), &[]);
    let list = build_trust_list(&TrustListSpec::new(vec![TlService::ca_qc(
        "openSzigno Test Qualified CA",
        pki.root_der.clone(),
    )]));
    let xml = dossier(signature(&pki), &pki.signer_key);
    let report = run_with_list(&xml, &list, None, AT);

    assert_check(&report, CheckCode::CertificateQualified, CheckStatus::Info);
    assert_eq!(report.signatures[0].qualified, Some(true));
}

/// A pre-eIDAS certificate is judged on the trusted list alone, because the
/// statement had not been mandated when it was issued.
#[test]
fn a_pre_eidas_certificate_is_judged_on_the_list_alone() {
    let pki = pki((2014, 1, 1), &[]);
    let mut service = TlService::ca_qc("openSzigno Test Qualified CA", pki.root_der.clone());
    service.status_starting_time = "2010-01-01T00:00:00Z".to_owned();
    let list = build_trust_list(&TrustListSpec::new(vec![service]));
    let xml = dossier(signature(&pki), &pki.signer_key);
    let report = run_with_list(&xml, &list, None, AT);

    assert_eq!(report.signatures[0].qualified, Some(true));
}

/// `QcSSCD` is reported as the qualified-device claim it is.
#[test]
fn a_qscd_statement_is_reported() {
    let pki = pki((2019, 1, 1), &["0.4.0.1862.1.1", "0.4.0.1862.1.4"]);
    let list = build_trust_list(&TrustListSpec::new(vec![TlService::ca_qc(
        "openSzigno Test Qualified CA",
        pki.root_der.clone(),
    )]));
    let xml = dossier(signature(&pki), &pki.signer_key);
    let report = run_with_list(&xml, &list, None, AT);

    assert_eq!(report.signatures[0].qualified, Some(true));
    assert_eq!(report.signatures[0].qualified_signature_device, Some(true));
    assert_eq!(
        report.signatures[0]
            .signing_certificate
            .as_ref()
            .and_then(|summary| summary.qualified),
        Some(true)
    );
}

/// A chain no trusted-list service covers is `false`, not `null`: a list was
/// consulted and did not vouch for it.
#[test]
fn a_chain_no_listed_service_covers_is_not_qualified() {
    let pki = pki((2019, 1, 1), &["0.4.0.1862.1.1"]);
    // The list names some *other* CA, so nothing in this chain is covered.
    let stranger = self_signed(
        &CertSpec::ca(
            "openSzigno Unrelated Qualified CA",
            BasicConstraints::Unconstrained,
        ),
        &rsa_key(keys::THIRD_RSA2048),
    );
    let mut trust = MemoryTrustStore::new(vec![pki.root_der.clone()], Vec::new());
    let list = build_trust_list(&TrustListSpec::new(vec![TlService::ca_qc(
        "openSzigno Unrelated Qualified CA",
        stranger.der,
    )]));
    let loaded = openszigno_verify::trustlist::load(list.as_bytes(), &[], &RoxmltreeC14n)
        .expect("the list loads");
    trust.extend_anchors(loaded.anchors);
    trust.extend_services(loaded.service_identities);

    let revocation = MemoryRevocationStore::default();
    let backend = RoxmltreeC14n;
    let clock = FixedClock(parse_rfc3339(AT).expect("the fixed time parses"));
    let mut options = VerifyOptions::new(&clock, &trust, &revocation, &backend);
    options.requested_time = Some(AT.to_owned());
    let xml = dossier(signature(&pki), &pki.signer_key);
    let report = verify(xml.as_bytes(), &options).expect("the dossier parses");

    assert_check(
        &report,
        CheckCode::CertificateNotQualified,
        CheckStatus::Info,
    );
    assert_eq!(report.signatures[0].qualified, Some(false));
}

/// With no trusted list at all the answer is "not determined", which the report
/// keeps distinct from "determined not to be qualified".
#[test]
fn a_trust_store_anchor_leaves_qualified_undetermined() {
    let pki = pki((2019, 1, 1), &["0.4.0.1862.1.1"]);
    let trust = MemoryTrustStore::new(vec![pki.root_der.clone()], Vec::new());
    let revocation = MemoryRevocationStore::default();
    let backend = RoxmltreeC14n;
    let clock = FixedClock(parse_rfc3339(AT).expect("the fixed time parses"));
    let mut options = VerifyOptions::new(&clock, &trust, &revocation, &backend);
    options.requested_time = Some(AT.to_owned());
    let xml = dossier(signature(&pki), &pki.signer_key);
    let report = verify(xml.as_bytes(), &options).expect("the dossier parses");

    assert_check(
        &report,
        CheckCode::CertificateQualifiedUnknown,
        CheckStatus::Info,
    );
    assert_eq!(report.signatures[0].qualified, None);
}

// ---------------------------------------------------------------------------
// The list's own signature
// ---------------------------------------------------------------------------

/// Without a signer certificate the list is read but reported as unverified,
/// which is blocking: a list that could be anyone's cannot support `valid`.
#[test]
fn an_unverified_list_blocks_the_verdict() {
    let pki = pki((2019, 1, 1), &["0.4.0.1862.1.1"]);
    let list = build_trust_list(&TrustListSpec::new(vec![TlService::ca_qc(
        "openSzigno Test Qualified CA",
        pki.root_der.clone(),
    )]));
    let xml = dossier(signature(&pki), &pki.signer_key);
    let report = run_with_list(&xml, &list, None, AT);

    assert_check(
        &report,
        CheckCode::TrustListUnverified,
        CheckStatus::Unknown,
    );
    assert_eq!(report.verdict, openszigno_verify::Verdict::Indeterminate);
}

/// With the right signer certificate, the list's own XMLDSig signature
/// verifies through the same core the dossier pipeline uses.
#[test]
fn a_signed_list_verifies_against_its_signer() {
    let pki = pki((2019, 1, 1), &["0.4.0.1862.1.1"]);
    let mut spec = TrustListSpec::new(vec![TlService::ca_qc(
        "openSzigno Test Qualified CA",
        pki.root_der.clone(),
    )]);
    spec.signer = Some((rsa_key(keys::SECOND_RSA2048), pki.tl_signer_der.clone()));
    let list = build_trust_list(&spec);
    let xml = dossier(signature(&pki), &pki.signer_key);
    let report = run_with_list(&xml, &list, Some(&pki.tl_signer_der), AT);

    assert_check(
        &report,
        CheckCode::TrustListSignatureOk,
        CheckStatus::Passed,
    );
}

/// A list changed after it was signed does not verify, and the failure is a
/// failure rather than an "unknown".
#[test]
fn a_tampered_list_fails_its_signature_check() {
    let pki = pki((2019, 1, 1), &["0.4.0.1862.1.1"]);
    let mut spec = TrustListSpec::new(vec![TlService::ca_qc(
        "openSzigno Test Qualified CA",
        pki.root_der.clone(),
    )]);
    spec.signer = Some((rsa_key(keys::SECOND_RSA2048), pki.tl_signer_der.clone()));
    spec.tamper = true;
    let list = build_trust_list(&spec);
    let xml = dossier(signature(&pki), &pki.signer_key);
    let report = run_with_list(&xml, &list, Some(&pki.tl_signer_der), AT);

    assert_check(
        &report,
        CheckCode::TrustListSignatureInvalid,
        CheckStatus::Failed,
    );
    assert_eq!(report.verdict, openszigno_verify::Verdict::Invalid);
}

/// A list signed by one key and checked against another certificate does not
/// verify either.
#[test]
fn a_list_signed_by_the_wrong_key_fails() {
    let pki = pki((2019, 1, 1), &["0.4.0.1862.1.1"]);
    let mut spec = TrustListSpec::new(vec![TlService::ca_qc(
        "openSzigno Test Qualified CA",
        pki.root_der.clone(),
    )]);
    // Signed with a third key, checked against the declared signer's
    // certificate.
    spec.signer = Some((rsa_key(keys::THIRD_RSA2048), pki.tl_signer_der.clone()));
    let list = build_trust_list(&spec);
    let xml = dossier(signature(&pki), &pki.signer_key);
    let report = run_with_list(&xml, &list, Some(&pki.tl_signer_der), AT);

    assert_check(
        &report,
        CheckCode::TrustListSignatureInvalid,
        CheckStatus::Failed,
    );
}

/// A list that carries no signature at all, checked against a signer, is a
/// failure and not a silent pass.
#[test]
fn a_list_with_no_signature_fails_when_one_is_demanded() {
    let pki = pki((2019, 1, 1), &["0.4.0.1862.1.1"]);
    let list = build_trust_list(&TrustListSpec::new(vec![TlService::ca_qc(
        "openSzigno Test Qualified CA",
        pki.root_der.clone(),
    )]));
    let loaded = openszigno_verify::trustlist::load(
        list.as_bytes(),
        std::slice::from_ref(&pki.tl_signer_der),
        &RoxmltreeC14n,
    )
    .expect("the list still loads");
    assert!(
        loaded
            .checks
            .iter()
            .any(|check| check.code == CheckCode::TrustListSignatureInvalid),
        "an unsigned list must not pass a signature check that was demanded"
    );
}

// ---------------------------------------------------------------------------
// The list signature's own structural rules
// ---------------------------------------------------------------------------

/// A signed list, edited so that one part of its `ds:Signature` is wrong. Every
/// case below must be refused *before* the signature itself is checked, so a
/// caller learns which rule the list broke rather than only that a signature
/// did not verify.
fn signed_list(pki: &Pki) -> String {
    let mut spec = TrustListSpec::new(vec![TlService::ca_qc(
        "openSzigno Test Qualified CA",
        pki.root_der.clone(),
    )]);
    spec.signer = Some((rsa_key(keys::SECOND_RSA2048), pki.tl_signer_der.clone()));
    build_trust_list(&spec)
}

fn signature_check(list: &str, signer: &[u8]) -> openszigno_verify::codes::Check {
    let loaded =
        openszigno_verify::trustlist::load(list.as_bytes(), &[signer.to_vec()], &RoxmltreeC14n)
            .expect("the list still parses");
    loaded
        .checks
        .into_iter()
        .find(|check| {
            matches!(
                check.code,
                CheckCode::TrustListSignatureOk | CheckCode::TrustListSignatureInvalid
            )
        })
        .expect("a signature check is always emitted when a signer is given")
}

#[test]
fn the_list_signature_rules_are_each_reported() {
    let pki = pki((2019, 1, 1), &[]);
    let list = signed_list(&pki);

    for (edited, expected) in [
        (
            list.replace("<ds:SignedInfo>", "<ds:SignedInfoX>")
                .replace("</ds:SignedInfo>", "</ds:SignedInfoX>"),
            "has no ds:SignedInfo",
        ),
        (
            list.replace("<ds:SignatureValue>", "<ds:SignatureValueX>")
                .replace("</ds:SignatureValue>", "</ds:SignatureValueX>"),
            "has no ds:SignatureValue",
        ),
        (
            list.replace(
                "Algorithm=\"http://www.w3.org/2001/10/xml-exc-c14n#\"/><ds:SignatureMethod",
                "Algorithm=\"http://www.w3.org/2006/12/xml-c14n11\"/><ds:SignatureMethod",
            ),
            "canonicalization method outside the allowlist",
        ),
        (
            list.replace(
                "http://www.w3.org/2001/04/xmldsig-more#rsa-sha256",
                "http://www.w3.org/2000/09/xmldsig#rsa-sha1",
            ),
            "signature method outside the allowlist",
        ),
        (
            list.replace("<ds:Reference URI=\"\">", "<ds:ReferenceX URI=\"\">")
                .replace("</ds:Reference>", "</ds:ReferenceX>"),
            "carries no ds:Reference",
        ),
        (
            list.replace(
                "Algorithm=\"http://www.w3.org/2001/10/xml-exc-c14n#\"/></ds:Transforms>",
                "Algorithm=\"http://www.w3.org/TR/1999/REC-xslt-19991116\"/></ds:Transforms>",
            ),
            "transform outside the allowlist",
        ),
        (
            list.replace(
                "<ds:DigestMethod Algorithm=\"http://www.w3.org/2001/04/xmlenc#sha256\"/>",
                "<ds:DigestMethod Algorithm=\"http://www.w3.org/2000/09/xmldsig#sha1\"/>",
            ),
            "digest outside the allowlist",
        ),
    ] {
        let check = signature_check(&edited, &pki.tl_signer_der);
        assert_eq!(check.code, CheckCode::TrustListSignatureInvalid);
        assert!(check.message.contains(expected), "{}", check.message);
    }
}

/// A reference that covers only part of the list leaves the service entries
/// unprotected, and is refused for that reason and not for a digest mismatch.
#[test]
fn a_signature_that_covers_only_part_of_the_list_is_refused() {
    let pki = pki((2019, 1, 1), &[]);
    // Two signatures is one of the shapes a partial-coverage attack takes, and
    // is refused before anything else is looked at.
    let list = signed_list(&pki);
    let doubled = list.replace(
        "</tsl:TrustServiceProviderList>",
        "</tsl:TrustServiceProviderList><ds:Signature xmlns:ds=\"http://www.w3.org/2000/09/xmldsig#\" Id=\"decoy\"/>",
    );
    let check = signature_check(&doubled, &pki.tl_signer_der);
    assert_eq!(check.code, CheckCode::TrustListSignatureInvalid);
    assert!(
        check.message.contains("exactly one ds:Signature"),
        "{}",
        check.message
    );
}

/// A `--trust-list-signer` file that is not a certificate is refused, rather
/// than being read as "no signer was given".
#[test]
fn a_signer_that_is_not_a_certificate_is_refused() {
    let pki = pki((2019, 1, 1), &[]);
    let check = signature_check(&signed_list(&pki), b"not a certificate");
    assert_eq!(check.code, CheckCode::TrustListSignatureInvalid);
    assert!(
        check
            .message
            .contains("no supplied trust-list signer is a usable X.509 certificate"),
        "{}",
        check.message
    );
}

/// A `ds:SignatureValue` that is not Base64 is a malformed signature, not an
/// unverifiable one.
#[test]
fn a_signature_value_that_is_not_base64_is_refused() {
    let pki = pki((2019, 1, 1), &[]);
    let list = signed_list(&pki);
    let start = list
        .find("<ds:SignatureValue>")
        .expect("the element exists")
        + "<ds:SignatureValue>".len();
    let end = list
        .find("</ds:SignatureValue>")
        .expect("the element exists");
    let edited = format!("{}not base64!!{}", &list[..start], &list[end..]);
    let check = signature_check(&edited, &pki.tl_signer_der);
    assert_eq!(check.code, CheckCode::TrustListSignatureInvalid);
    assert!(check.message.contains("not Base64"), "{}", check.message);
}

/// The service-type names are stable strings.
#[test]
fn service_type_names_are_stable() {
    use openszigno_verify::ServiceType;
    assert_eq!(ServiceType::CaQc.as_str(), "ca_qc");
    assert_eq!(ServiceType::TsaQtst.as_str(), "tsa_qtst");
}

// ---------------------------------------------------------------------------
// The determination is about the chain, not about the anchor
// ---------------------------------------------------------------------------

/// A root, an issuing CA, and a signer under the issuing CA. This is the shape
/// every real Hungarian dossier has: the root is a certificate an operator
/// pins, and the *issuing* CA is what the trusted list names as a CA/QC
/// service.
struct Hierarchy {
    root_der: Vec<u8>,
    intermediate_der: Vec<u8>,
    signer_der: Vec<u8>,
    signer_key: TestKey,
}

fn hierarchy(qc: &[&str]) -> Hierarchy {
    let root_key = rsa_key(keys::ROOT_RSA2048);
    let intermediate_key = rsa_key(keys::INTERMEDIATE_RSA2048);
    let signer_key = rsa_key(keys::SIGNER_RSA2048);
    let root = self_signed(
        &CertSpec::ca("openSzigno Test Root", BasicConstraints::Unconstrained),
        &root_key,
    );
    let intermediate = issued_by(
        &CertSpec::ca(
            "Qualified openSzigno CA 2009",
            BasicConstraints::Constrained(0),
        ),
        &intermediate_key,
        &root,
        &root_key,
    );
    let mut signer_spec = CertSpec::signer("openSzigno Test Signer");
    if !qc.is_empty() {
        signer_spec.custom_extensions = vec![qc_statements_extension(qc)];
    }
    let signer = issued_by(&signer_spec, &signer_key, &intermediate, &intermediate_key);
    Hierarchy {
        root_der: root.der,
        intermediate_der: intermediate.der,
        signer_der: signer.der,
        signer_key,
    }
}

fn hierarchy_dossier(pki: &Hierarchy) -> String {
    let mut signature = document_signature(vec![pki.signer_der.clone()]);
    signature.signing_certificate = Some(SigningCertificateSpec::v1(pki.signer_der.clone()));
    signature.certificate_values = vec![pki.intermediate_der.clone()];
    let spec = DossierSpec {
        document_signature: Some(signature),
        ..Default::default()
    };
    build(&spec, &[("doc", &pki.signer_key)])
}

/// Verify with the root pinned in a `--trust-store` and the trusted list
/// naming whichever certificate the test chooses.
fn run_store_and_list(xml: &str, root_der: Vec<u8>, list: &str, time: &str) -> VerifyReport {
    let backend = RoxmltreeC14n;
    let mut trust = MemoryTrustStore::new(vec![root_der], Vec::new());
    let loaded = openszigno_verify::trustlist::load(list.as_bytes(), &[], &backend)
        .expect("the synthetic trusted list loads");
    for check in loaded.checks {
        trust.push_check(check);
    }
    trust.extend_anchors(loaded.anchors);
    trust.extend_services(loaded.service_identities);

    let revocation = MemoryRevocationStore::default();
    let clock = FixedClock(parse_rfc3339(time).expect("the fixed time parses"));
    let mut options = VerifyOptions::new(&clock, &trust, &revocation, &backend);
    options.requested_time = Some(time.to_owned());
    verify(xml.as_bytes(), &options).expect("the dossier parses structurally")
}

/// The trusted list names the **issuing CA**, not the root, and the root came
/// from a directory. Asking only the anchor would report "not determined";
/// asking the chain gets the right answer, which is the whole reason a trusted
/// list is loaded.
#[test]
fn a_listed_intermediate_qualifies_the_chain() {
    let pki = hierarchy(&["0.4.0.1862.1.1", "0.4.0.1862.1.4"]);
    let list = build_trust_list(&TrustListSpec::new(vec![TlService::ca_qc(
        "Qualified openSzigno CA 2009",
        pki.intermediate_der.clone(),
    )]));
    let report = run_store_and_list(&hierarchy_dossier(&pki), pki.root_der.clone(), &list, AT);

    assert_check(&report, CheckCode::CertPathOk, CheckStatus::Passed);
    assert_check(&report, CheckCode::CertificateQualified, CheckStatus::Info);
    assert_eq!(report.signatures[0].qualified, Some(true));
    assert_eq!(report.signatures[0].qualified_signature_device, Some(true));
    // The matched service is named, because a caller must be able to check the
    // determination against the list themselves.
    assert_eq!(
        report.signatures[0].qualified_service.as_deref(),
        Some("Qualified openSzigno CA 2009")
    );
    // The anchor is still the store's root, and is reported as such.
    assert_eq!(
        report.signatures[0]
            .chain
            .last()
            .and_then(|entry| entry.trust_anchor_origin),
        Some(TrustAnchorOrigin::TrustStore)
    );
}

/// A service identity that is not in the chain but *issued* a certificate in
/// it also covers the chain — and "issued" is a verified signature, so naming
/// the right issuer is not enough.
#[test]
fn a_service_identity_that_issued_a_chain_certificate_covers_it() {
    let pki = hierarchy(&["0.4.0.1862.1.1"]);
    // The list names the root, which issued the intermediate in the chain. The
    // root is also the store anchor, so this exercises the equals-DER branch
    // and the origin preference below.
    let list = build_trust_list(&TrustListSpec::new(vec![TlService::ca_qc(
        "openSzigno Test Root",
        pki.root_der.clone(),
    )]));
    let report = run_store_and_list(&hierarchy_dossier(&pki), pki.root_der.clone(), &list, AT);

    assert_eq!(report.signatures[0].qualified, Some(true));
    // The same certificate is both a store anchor and a trusted-list identity.
    // The list is the stronger provenance and the one worth reporting.
    assert_eq!(
        report.signatures[0]
            .chain
            .last()
            .and_then(|entry| entry.trust_anchor_origin),
        Some(TrustAnchorOrigin::TrustList)
    );
}

/// A certificate that merely *claims* a listed issuer is not covered by it:
/// the match is a verified signature.
#[test]
fn a_name_match_alone_does_not_qualify_a_chain() {
    let pki = hierarchy(&["0.4.0.1862.1.1"]);
    // An impostor with the issuing CA's exact distinguished name and a
    // different key. Nothing in the validated chain equals it, and nothing in
    // the chain verifies against its key.
    let impostor = self_signed(
        &CertSpec::ca(
            "Qualified openSzigno CA 2009",
            BasicConstraints::Unconstrained,
        ),
        &rsa_key(keys::THIRD_RSA2048),
    );
    let list = build_trust_list(&TrustListSpec::new(vec![TlService::ca_qc(
        "Qualified openSzigno CA 2009",
        impostor.der,
    )]));
    let report = run_store_and_list(&hierarchy_dossier(&pki), pki.root_der.clone(), &list, AT);

    assert_check(&report, CheckCode::CertPathOk, CheckStatus::Passed);
    assert_check(
        &report,
        CheckCode::CertificateNotQualified,
        CheckStatus::Info,
    );
    assert_eq!(report.signatures[0].qualified, Some(false));
    assert_eq!(report.signatures[0].qualified_service, None);
}

/// A listed intermediate whose service was withdrawn before the validation
/// time no longer qualifies the chain, even though the path still builds.
#[test]
fn a_withdrawn_intermediate_service_does_not_qualify() {
    let pki = hierarchy(&["0.4.0.1862.1.1"]);
    let mut service =
        TlService::ca_qc("Qualified openSzigno CA 2009", pki.intermediate_der.clone());
    service.status = STATUS_WITHDRAWN.to_owned();
    service.status_starting_time = "2021-01-01T00:00:00Z".to_owned();
    service.history = vec![(STATUS_GRANTED.to_owned(), "2016-07-01T00:00:00Z".to_owned())];
    let list = build_trust_list(&TrustListSpec::new(vec![service]));
    let dossier = hierarchy_dossier(&pki);

    // While the service was granted, the chain qualifies.
    let report = run_store_and_list(&dossier, pki.root_der.clone(), &list, AT);
    assert_check(&report, CheckCode::CertPathOk, CheckStatus::Passed);
    assert_eq!(report.signatures[0].qualified, Some(true));

    // After the withdrawal the path still builds — the certificates are as
    // valid as they were — but the chain is no longer qualified.
    let report = run_store_and_list(
        &dossier,
        pki.root_der.clone(),
        &list,
        "2022-01-01T00:00:00Z",
    );
    assert_check(&report, CheckCode::CertPathOk, CheckStatus::Passed);
    assert_eq!(report.signatures[0].qualified, Some(false));
}

// ---------------------------------------------------------------------------
// Bootstrapping national lists from the list of trusted lists
// ---------------------------------------------------------------------------

/// The EU list of trusted lists names, in its `PointersToOtherTSL`, the signing
/// certificates of the national lists. One out-of-band certificate — the
/// LOTL's, from the Official Journal — therefore bootstraps the verification of
/// every member state's list, which is the only chain of trust that means
/// anything here.
#[test]
fn the_lotl_pointers_verify_a_national_list() {
    let pki = pki((2019, 1, 1), &["0.4.0.1862.1.1"]);

    // The national list, signed with a key only its own pointer names.
    let national_signer_key = rsa_key(keys::THIRD_RSA2048);
    let national_signer = self_signed(
        &CertSpec::signer("openSzigno Test HU List Signer"),
        &national_signer_key,
    );
    let mut national = TrustListSpec::new(vec![TlService::ca_qc(
        "openSzigno Test Qualified CA",
        pki.root_der.clone(),
    )]);
    national.signer = Some((rsa_key(keys::THIRD_RSA2048), national_signer.der.clone()));
    let national_xml = build_trust_list(&national);

    // The LOTL, signed with the certificate the caller holds out of band, and
    // pointing at the national list's signer.
    let mut lotl = TrustListSpec::new(Vec::new());
    lotl.signer = Some((rsa_key(keys::SECOND_RSA2048), pki.tl_signer_der.clone()));
    lotl.pointers = vec![national_signer.der.clone()];
    let lotl_xml = build_trust_list(&lotl);

    let loaded_lotl = openszigno_verify::trustlist::load(
        lotl_xml.as_bytes(),
        std::slice::from_ref(&pki.tl_signer_der),
        &RoxmltreeC14n,
    )
    .expect("the LOTL loads");
    assert!(
        loaded_lotl
            .checks
            .iter()
            .any(|check| check.code == CheckCode::TrustListSignatureOk),
        "the LOTL must verify against the out-of-band certificate"
    );
    assert_eq!(loaded_lotl.pointer_certificates.len(), 1);
    // The LOTL itself lists no CA/QC service, so it contributes no anchors.
    assert!(loaded_lotl.anchors.is_empty());

    let loaded_national = openszigno_verify::trustlist::load(
        national_xml.as_bytes(),
        &loaded_lotl.pointer_certificates,
        &RoxmltreeC14n,
    )
    .expect("the national list loads");
    assert!(
        loaded_national
            .checks
            .iter()
            .any(|check| check.code == CheckCode::TrustListSignatureOk),
        "a pointer certificate must verify the national list"
    );

    // And a national list the pointers do not name is refused, so the pointer
    // set is a real restriction rather than a formality.
    let mut impostor = TrustListSpec::new(vec![TlService::ca_qc(
        "openSzigno Test Qualified CA",
        pki.root_der.clone(),
    )]);
    impostor.signer = Some((rsa_key(keys::SECOND_RSA2048), pki.tl_signer_der.clone()));
    let loaded_impostor = openszigno_verify::trustlist::load(
        build_trust_list(&impostor).as_bytes(),
        &loaded_lotl.pointer_certificates,
        &RoxmltreeC14n,
    )
    .expect("the list still parses");
    assert!(
        loaded_impostor
            .checks
            .iter()
            .any(|check| check.code == CheckCode::TrustListSignatureInvalid),
        "a list signed by a certificate no pointer names must not verify"
    );
}

// ---------------------------------------------------------------------------
// M3: the identity forms a real list uses beyond `X509Certificate`
// ---------------------------------------------------------------------------

/// A PKI whose root and signer are both valid from 2009, so a pre-eIDAS
/// validation time can be used without the chain failing on validity.
fn historic_pki() -> Pki {
    let root_key = rsa_key(keys::ROOT_RSA2048);
    let signer_key = rsa_key(keys::SIGNER_RSA2048);
    let mut root_spec = CertSpec::ca(
        "openSzigno Test Qualified CA",
        BasicConstraints::Unconstrained,
    );
    root_spec.not_before = (2009, 1, 1);
    let root = self_signed(&root_spec, &root_key);
    let mut signer_spec = CertSpec::signer("openSzigno Test Signer");
    signer_spec.not_before = (2009, 1, 1);
    let signer = issued_by(&signer_spec, &signer_key, &root, &root_key);
    let tl_signer = self_signed(
        &CertSpec::signer("openSzigno Test Trusted List Signer"),
        &rsa_key(keys::SECOND_RSA2048),
    );
    Pki {
        root_der: root.der,
        signer_der: signer.der,
        signer_key,
        tl_signer_der: tl_signer.der,
    }
}

/// One certificate's subject as the RFC 4514 string a list operator would
/// write into an `X509SubjectName` identity.
fn subject_name_of(der: &[u8]) -> String {
    ParsedCertificate::from_der(der, CertificateSource::TrustStore)
        .expect("the certificate parses")
        .certificate
        .tbs_certificate
        .subject
        .to_string()
}

/// The raw `subjectKeyIdentifier` of one certificate.
fn ski_of(der: &[u8]) -> Vec<u8> {
    ParsedCertificate::from_der(der, CertificateSource::TrustStore)
        .expect("the certificate parses")
        .subject_key_identifier()
        .expect("rcgen writes a subjectKeyIdentifier")
}

/// A service whose only digital identity is an `X509SKI` supplies no anchor —
/// it names a certificate without carrying one — but it can still say that a
/// chain some other anchor validated is covered by a granted CA/QC service.
#[test]
fn an_x509_ski_identity_qualifies_a_chain_it_names() {
    let pki = hierarchy(&["0.4.0.1862.1.1"]);
    let list = build_trust_list(&TrustListSpec::new(vec![TlService::by_ski(
        "Qualified openSzigno CA 2009",
        ski_of(&pki.intermediate_der),
    )]));
    let report = run_store_and_list(&hierarchy_dossier(&pki), pki.root_der.clone(), &list, AT);

    assert_check(&report, CheckCode::CertificateQualified, CheckStatus::Info);
    assert_eq!(report.signatures[0].qualified, Some(true));
    // The report says *how* the determination was reached, because an SKI
    // match is weaker evidence than a certificate identity.
    let check = report.signatures[0]
        .checks
        .iter()
        .find(|check| check.code == CheckCode::CertificateQualified)
        .expect("the qualified check is present");
    assert!(check.message.contains("X509SKI"), "{}", check.message);
    // The anchor is still the store's root: an SKI grants nothing.
    assert_eq!(
        report.signatures[0]
            .chain
            .last()
            .and_then(|entry| entry.trust_anchor_origin),
        Some(TrustAnchorOrigin::TrustStore)
    );
}

/// An SKI that belongs to no certificate in the chain decides nothing.
#[test]
fn an_x509_ski_identity_that_names_nothing_does_not_qualify() {
    let pki = hierarchy(&["0.4.0.1862.1.1"]);
    let list = build_trust_list(&TrustListSpec::new(vec![TlService::by_ski(
        "Some Other CA",
        vec![0xaa; 20],
    )]));
    let report = run_store_and_list(&hierarchy_dossier(&pki), pki.root_der.clone(), &list, AT);

    assert_check(
        &report,
        CheckCode::CertificateNotQualified,
        CheckStatus::Info,
    );
    assert_eq!(report.signatures[0].qualified, Some(false));
}

/// An `X509SubjectName` identity is matched by DER-exact subject, never by
/// string comparison.
#[test]
fn an_x509_subject_name_identity_qualifies_a_chain_it_names() {
    let pki = hierarchy(&["0.4.0.1862.1.1"]);
    let list = build_trust_list(&TrustListSpec::new(vec![TlService::by_subject_name(
        "Qualified openSzigno CA 2009",
        &subject_name_of(&pki.intermediate_der),
    )]));
    let report = run_store_and_list(&hierarchy_dossier(&pki), pki.root_der.clone(), &list, AT);

    assert_check(&report, CheckCode::CertificateQualified, CheckStatus::Info);
    assert_eq!(report.signatures[0].qualified, Some(true));
    let check = report.signatures[0]
        .checks
        .iter()
        .find(|check| check.code == CheckCode::CertificateQualified)
        .expect("the qualified check is present");
    assert!(
        check.message.contains("X509SubjectName"),
        "{}",
        check.message
    );
}

/// A subject name that differs in any way — here one attribute value — does
/// not match, because the comparison is on DER and nothing is normalised.
#[test]
fn a_subject_name_that_is_not_der_identical_does_not_qualify() {
    let pki = hierarchy(&["0.4.0.1862.1.1"]);
    let list = build_trust_list(&TrustListSpec::new(vec![TlService::by_subject_name(
        "Nearly Right",
        &subject_name_of(&pki.intermediate_der).replace("2009", "2010"),
    )]));
    let report = run_store_and_list(&hierarchy_dossier(&pki), pki.root_der.clone(), &list, AT);

    assert_eq!(report.signatures[0].qualified, Some(false));
}

// ---------------------------------------------------------------------------
// M3: the pre-eIDAS statuses, honoured for their historical window only
// ---------------------------------------------------------------------------

/// A signature made in 2014 under a supervised CA was made under exactly what
/// a member state published for a qualified issuer at the time. The status is
/// honoured at a validation time before eIDAS applied, and the report names it.
#[test]
fn under_supervision_is_granted_before_eidas_applied() {
    let pki = historic_pki();
    let mut service = TlService::ca_qc("openSzigno Test Qualified CA", pki.root_der.clone());
    service.status = STATUS_UNDER_SUPERVISION.to_owned();
    service.status_starting_time = "2009-01-01T00:00:00Z".to_owned();
    let list = build_trust_list(&TrustListSpec::new(vec![service]));
    let xml = dossier(signature(&pki), &pki.signer_key);

    let report = run_with_list(&xml, &list, None, "2014-01-01T00:00:00Z");
    assert_eq!(report.signatures[0].qualified, Some(true));
    let check = report.signatures[0]
        .checks
        .iter()
        .find(|check| check.code == CheckCode::CertificateQualified)
        .expect("the qualified check is present");
    assert!(
        check.message.contains("undersupervision"),
        "the status that was honoured is named: {}",
        check.message
    );
}

/// The same for `accredited`, the other pre-eIDAS vocabulary entry.
#[test]
fn accredited_is_granted_before_eidas_applied() {
    let pki = historic_pki();
    let mut service = TlService::ca_qc("openSzigno Test Qualified CA", pki.root_der.clone());
    service.status = STATUS_ACCREDITED.to_owned();
    service.status_starting_time = "2009-01-01T00:00:00Z".to_owned();
    let list = build_trust_list(&TrustListSpec::new(vec![service]));
    let xml = dossier(signature(&pki), &pki.signer_key);

    let report = run_with_list(&xml, &list, None, "2014-01-01T00:00:00Z");
    assert_eq!(report.signatures[0].qualified, Some(true));
    let check = report.signatures[0]
        .checks
        .iter()
        .find(|check| check.code == CheckCode::CertificateQualified)
        .expect("the qualified check is present");
    assert!(check.message.contains("accredited"), "{}", check.message);
}

/// A service left at a pre-eIDAS status once the eIDAS vocabulary applied has
/// not been granted under it, so the window closes on 2016-07-01.
#[test]
fn a_pre_eidas_status_stops_being_granted_when_eidas_applies() {
    let pki = historic_pki();
    let mut service = TlService::ca_qc("openSzigno Test Qualified CA", pki.root_der.clone());
    service.status = STATUS_ACCREDITED.to_owned();
    service.status_starting_time = "2009-01-01T00:00:00Z".to_owned();
    let list = build_trust_list(&TrustListSpec::new(vec![service]));
    let xml = dossier(signature(&pki), &pki.signer_key);

    let before = run_with_list(&xml, &list, None, "2016-06-30T00:00:00Z");
    assert_eq!(before.signatures[0].qualified, Some(true));
    let after = run_with_list(&xml, &list, None, "2016-07-01T00:00:00Z");
    assert_eq!(after.signatures[0].qualified, Some(false));
}

// ---------------------------------------------------------------------------
// M3: service names
// ---------------------------------------------------------------------------

/// A national list writes its own language first. The English name is the one
/// worth reporting to an operator, so it wins over document order.
#[test]
fn the_english_service_name_is_preferred() {
    let pki = pki((2019, 1, 1), &["0.4.0.1862.1.1"]);
    let mut service = TlService::ca_qc("Qualified Certification Authority", pki.root_der.clone());
    service.extra_names = vec![
        (
            "hu".to_owned(),
            "Minositett Hitelesitesszolgaltato".to_owned(),
        ),
        (
            "de".to_owned(),
            "Qualifizierte Zertifizierungsstelle".to_owned(),
        ),
    ];
    let list = build_trust_list(&TrustListSpec::new(vec![service]));
    let xml = dossier(signature(&pki), &pki.signer_key);

    let report = run_with_list(&xml, &list, None, AT);
    assert_eq!(
        report.signatures[0].qualified_service.as_deref(),
        Some("Qualified Certification Authority")
    );
}
