//! The certificate that signed a trusted list: the signed
//! `xades:SigningCertificateV2` binding, and the ETSI TS 119 612 clause 5.7.1
//! restrictions on a scheme operator's certificate.
//!
//! Every list here is generated by the test helper, and every certificate by
//! the synthetic test PKI. Nothing is derived from a real trusted list or a
//! real trust service provider.

mod common;

use common::{
    CertSpec, SigningCertificateSpec, TlService, TrustListSpec, build_trust_list,
    extended_key_usage_extension, issued_by, keys, rsa_key, self_signed,
};
use openszigno_verify::codes::{Check, CheckCode, CheckStatus};
use openszigno_verify::{RoxmltreeC14n, trustlist};
use rcgen::{BasicConstraints, KeyUsagePurpose};

/// `id-tsl-kp-tslSigning`, ETSI TS 119 612 clause 5.7.1.
const OID_TSL_SIGNING: &str = "0.4.0.2231.3.0";

/// A scheme operator certificate as clause 5.7.1 wants one: `CA=false`, a
/// `keyUsage` of `digitalSignature` and `nonRepudiation`, and the
/// `id-tsl-kp-tslSigning` extended key usage.
fn tlso_spec(common_name: &str) -> CertSpec<'_> {
    let mut spec = CertSpec::signer(common_name);
    spec.custom_extensions = vec![extended_key_usage_extension(&[OID_TSL_SIGNING], false)];
    spec
}

/// One list, signed by the key behind `signer_der`, optionally binding
/// `bind` through a signed `xades:SigningCertificateV2`.
fn list_signed_by(signer_der: &[u8], bind: Option<&[u8]>, services: Vec<TlService>) -> String {
    let mut spec = TrustListSpec::new(services);
    spec.signer = Some((rsa_key(keys::SECOND_RSA2048), signer_der.to_vec()));
    spec.signing_certificate = bind.map(|der| SigningCertificateSpec::v2(der.to_vec()));
    build_trust_list(&spec)
}

/// The checks one list produced when read against one signer certificate.
fn checks(list: &str, signer: &[u8]) -> Vec<Check> {
    trustlist::load(list.as_bytes(), &[signer.to_vec()], &RoxmltreeC14n)
        .expect("the synthetic trusted list loads")
        .checks
}

fn seen(checks: &[Check]) -> Vec<String> {
    checks
        .iter()
        .map(|check| format!("{}={}", check.code.as_str(), check.status.as_str()))
        .collect()
}

fn find(checks: &[Check], code: CheckCode) -> Vec<&Check> {
    checks.iter().filter(|check| check.code == code).collect()
}

fn assert_none(checks: &[Check], code: CheckCode) {
    assert!(
        find(checks, code).is_empty(),
        "expected no {}; got {:?}",
        code.as_str(),
        seen(checks)
    );
}

/// A compliant scheme operator certificate, bound by the list's own signed
/// property, produces the signature check and nothing else. This is the shape
/// both live EU lists have, and it must stay quiet.
#[test]
fn a_compliant_signer_bound_by_the_list_reports_nothing_extra() {
    let signer = self_signed(
        &tlso_spec("openSzigno Test TLSO"),
        &rsa_key(keys::SECOND_RSA2048),
    );
    let list = list_signed_by(&signer.der, Some(&signer.der), Vec::new());
    let checks = checks(&list, &signer.der);

    assert!(
        find(&checks, CheckCode::TrustListSignatureOk)
            .iter()
            .any(|check| check.status == CheckStatus::Passed),
        "the list's own signature must still verify: {:?}",
        seen(&checks)
    );
    assert_none(&checks, CheckCode::TrustListSignerMismatch);
    assert_none(&checks, CheckCode::TrustListSignerUnqualified);
}

/// The list's signed `SigningCertificateV2` names a certificate other than the
/// one the caller supplied. The caller and the list disagree about who signed,
/// and the list is treated as unverified rather than believed.
#[test]
fn a_binding_that_names_another_certificate_is_blocking() {
    let signer = self_signed(
        &tlso_spec("openSzigno Test TLSO"),
        &rsa_key(keys::SECOND_RSA2048),
    );
    let other = self_signed(
        &tlso_spec("openSzigno Test Other TLSO"),
        &rsa_key(keys::THIRD_RSA2048),
    );
    let list = list_signed_by(&signer.der, Some(&other.der), Vec::new());
    let checks = checks(&list, &signer.der);

    let mismatch = find(&checks, CheckCode::TrustListSignerMismatch);
    assert_eq!(
        mismatch.len(),
        1,
        "the binding mismatch must be reported once: {:?}",
        seen(&checks)
    );
    assert_eq!(
        mismatch[0].status,
        CheckStatus::Unknown,
        "a signer the list itself does not name blocks a valid verdict"
    );
}

/// A list carrying no signed `SigningCertificate` property at all says nothing
/// about who signed it, so there is nothing to disagree with. TLv5 lists are
/// signed as XAdES-BES and need not carry one.
#[test]
fn a_list_without_the_property_reports_no_binding() {
    let signer = self_signed(
        &tlso_spec("openSzigno Test TLSO"),
        &rsa_key(keys::SECOND_RSA2048),
    );
    let list = list_signed_by(&signer.der, None, Vec::new());

    assert_none(
        &checks(&list, &signer.der),
        CheckCode::TrustListSignerMismatch,
    );
}

/// Clause 5.7.1 says the extended key usage "should" be present containing
/// `id-tsl-kp-tslSigning`. A certificate without it is reported and never
/// blocks: the European Commission's own LOTL signing certificate does not
/// carry it.
#[test]
fn a_signer_without_the_tsl_signing_key_purpose_is_reported_as_info() {
    let signer = self_signed(
        &CertSpec::signer("openSzigno Test TLSO"),
        &rsa_key(keys::SECOND_RSA2048),
    );
    let list = list_signed_by(&signer.der, Some(&signer.der), Vec::new());
    let checks = checks(&list, &signer.der);

    let reported = find(&checks, CheckCode::TrustListSignerUnqualified);
    assert_eq!(reported.len(), 1, "one rule failed: {:?}", seen(&checks));
    assert_eq!(reported[0].status, CheckStatus::Info);
    assert!(
        reported[0].message.contains("extendedKeyUsage"),
        "the message must name the requirement that failed: {}",
        reported[0].message
    );
    assert!(
        checks
            .iter()
            .all(|check| check.status != CheckStatus::Unknown),
        "scheme operator hygiene must not cap the verdict: {:?}",
        seen(&checks)
    );
}

/// An extended key usage naming other purposes is the same finding: nothing in
/// the certificate says this key may sign trusted lists.
#[test]
fn a_signer_whose_key_purposes_are_something_else_is_reported_as_info() {
    let mut spec = CertSpec::signer("openSzigno Test TLSO");
    spec.custom_extensions = vec![extended_key_usage_extension(&["1.3.6.1.5.5.7.3.2"], false)];
    let signer = self_signed(&spec, &rsa_key(keys::SECOND_RSA2048));
    let list = list_signed_by(&signer.der, Some(&signer.der), Vec::new());
    let checks = checks(&list, &signer.der);

    let reported = find(&checks, CheckCode::TrustListSignerUnqualified);
    assert_eq!(reported.len(), 1, "one rule failed: {:?}", seen(&checks));
    assert_eq!(reported[0].status, CheckStatus::Info);
    assert!(
        reported[0].message.contains("id-tsl-kp-tslSigning"),
        "the message must name the missing key purpose: {}",
        reported[0].message
    );
}

/// Clause 5.7.1 requires a `keyUsage` of `digitalSignature` and/or
/// `nonRepudiation`. One that is neither is reported, and only reported.
#[test]
fn a_signer_whose_key_usage_permits_neither_signing_form_is_reported_as_info() {
    let mut spec = tlso_spec("openSzigno Test TLSO");
    spec.key_usages = vec![KeyUsagePurpose::KeyEncipherment];
    let signer = self_signed(&spec, &rsa_key(keys::SECOND_RSA2048));
    let list = list_signed_by(&signer.der, Some(&signer.der), Vec::new());
    let checks = checks(&list, &signer.der);

    let reported = find(&checks, CheckCode::TrustListSignerUnqualified);
    assert!(
        reported
            .iter()
            .any(|check| check.message.contains("keyUsage") && check.status == CheckStatus::Info),
        "the keyUsage rule must be reported as info: {:?}",
        seen(&checks)
    );
}

/// Clause 5.7.1 requires `BasicConstraints` to indicate `CA=false`. A CA
/// certificate signing a list is reported, and only reported: what verified
/// the signature is the caller's own certificate.
#[test]
fn a_signer_that_is_a_ca_is_reported_as_info() {
    let mut spec = CertSpec::ca("openSzigno Test TLSO CA", BasicConstraints::Unconstrained);
    spec.custom_extensions = vec![extended_key_usage_extension(&[OID_TSL_SIGNING], false)];
    let signer = self_signed(&spec, &rsa_key(keys::SECOND_RSA2048));
    let list = list_signed_by(&signer.der, Some(&signer.der), Vec::new());
    let checks = checks(&list, &signer.der);

    let reported = find(&checks, CheckCode::TrustListSignerUnqualified);
    assert!(
        reported
            .iter()
            .any(|check| check.message.contains("basicConstraints")
                && check.status == CheckStatus::Info),
        "the CA=false rule must be reported as info: {:?}",
        seen(&checks)
    );
    assert!(
        checks
            .iter()
            .all(|check| check.status != CheckStatus::Unknown),
        "scheme operator hygiene must not cap the verdict: {:?}",
        seen(&checks)
    );
}

/// Clause 5.7.1 wants the issuer to be the scheme operator itself or a service
/// the list names. A signer issued by a certificate the list does not name is
/// reported; the same signer is quiet once its issuer is a listed service,
/// which is the half of the rule one file can answer.
#[test]
fn an_issuer_the_list_does_not_name_is_reported_until_the_list_names_it() {
    let issuer_key = rsa_key(keys::ROOT_RSA2048);
    let issuer = self_signed(
        &CertSpec::ca(
            "openSzigno Test TLSO Issuer",
            BasicConstraints::Unconstrained,
        ),
        &issuer_key,
    );
    let signer_key = rsa_key(keys::SECOND_RSA2048);
    let signer = issued_by(
        &tlso_spec("openSzigno Test TLSO"),
        &signer_key,
        &issuer,
        &issuer_key,
    );

    let unlisted = list_signed_by(&signer.der, Some(&signer.der), Vec::new());
    let reported = find(
        &checks(&unlisted, &signer.der),
        CheckCode::TrustListSignerUnqualified,
    )
    .iter()
    .any(|check| check.message.contains("self-signed") && check.status == CheckStatus::Info);
    assert!(reported, "an issuer no list names must be reported");

    let listed = list_signed_by(
        &signer.der,
        Some(&signer.der),
        vec![TlService::ca_qc(
            "openSzigno Test Qualified CA",
            issuer.der.clone(),
        )],
    );
    assert_none(
        &checks(&listed, &signer.der),
        CheckCode::TrustListSignerUnqualified,
    );
}
